### ISSUE TITLE
Add summaries API documentation

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#112]

**Comment by wilbertom** [comment]
`dailybookingscounts` and `dailypopulationcounts` are semantically identical. Both of them can be documented at the same time.

The only difference between the two is that `dailybookingscounts` has `female_minors` and `male_minors count`.

**Comment by eads** [comment]
Oh snap. Very glad you're tackling this...

On Sun, Aug 18, 2013 at 9:14 PM, Wilberto Morales
notifications@github.comwrote:

> dailybookingscounts and dailypopulationcounts are semantically identical.
> Both of them can be documented at the same time.
> 
> The only difference between the two is that dailybookingscounts has
> female_minors and male_minors count.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/112#issuecomment-22847570
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

Stay grimy!

**Comment by bepetersn** [comment]
That's interesting, that they were the same. That must mean there were no "booked" and "left" fields. Doing that sure would make the v2 summary API simpler... though bookings would only tell you the average population change.

**Comment by bepetersn** [comment]
This is no longer relevant, issue #397 should supercede it.
