### ISSUE TITLE
Look into unqiuely identifying individuals

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#116]
There could be a couple of approaches that are worth trying; either of which might allow us to begin to try to track recidivism in the CCJ:
- Hashing a name, birthdate, and race 
- Creating our own unique identifiers for an individual 

The tradeoffs aren't clear to me for preferring one over another. We could also use a similitude algorithm of some kind to try to match weights and heights.

**Comment by eads** [comment]
I'm not really clear on the second option. We don't have a clear unique D, like a social security number or an IR number. So it seems like uniquely identifying specific people has to depend on the first option in some form. The question, I think, is how that should work. This requires some research in naming + birthdate uniqueness, I suspect. 

Here's my assumptions about the problem:

Just a name and full birthdate are pretty unique. At the same time, there might have been a couple of Joe Johnson's born May 2, 1980. But are all of those Joe Johnson's likely to go to jail? I think not. So we could potentially create a hash with just that information, with small risk of over-counting.

Every other demographic field has serious flaws or unclear benefits in terms of uniquely identifying someone, and we need to talk to booking to understand better how they collect this info:

Weight: My professor's wife once said there were 50 pounds of Larry she wasn't legally married to. My driver's license says I'm 150 lbs. This seems completely untrustworthy.

Height: This won't change much... unless you're 17, in which case in even six months it could be different enough to count. I suspect we should include this at the risk of under-counting (a risk that's much more easily tolerated than over-counting).

Race: This seems solid enough, but then we've got a ridiculous amount of ambiguity in terms of people's races and how those are designated. If someone visits the jail a couple times, are they marked LT, LB, and LW on consecutive visits? 

Gender: There are almost certainly people who transition between genders between visits to the jail or are mis-gendered at booking, but my assumption is that for hashing purposes, that number must be so few as to essentially be noise in the data. Given that names have strong gender bias, I doubt including gender in the hash will greatly improve uniqueness, but of all the fields, it is the least likely to have errors and provide unique identification. Could two people named Cary Grant born on June 1, 1979 have both visited Cook County Jail? Far stranger things have happened.

For all of these fields, we need to understand better how they are collected at booking.

**Comment by bepetersn** [comment]
Well, my understanding is basically the same on all these things. One easy thing Matt suggested would be to take only the first letter of the race code, so: "L" for "LT", "LW", or "LB". That would also us to make a hash based on name, birthdate, and race. So for instance we could hash the string "BrianPeterson080493W", or something like that.

How does that sound? It's easy, regardless. I'm just trying to conceptualize at what points in our programs this processing needs to be integrated.

**Comment by eads** [comment]
The first letter of race is interesting. I don't see why not... The risk of
collisions seems very small. Also let's include gender in that string.

**Comment by bepetersn** [comment]
What I'm curious to know right now is if we currently have representations for people with the exact same name and birthdate but different other fields like booking_date in our database. I'd like a sense for the kinds of recidivism in our system we might be catching. But 48,000 x 48,000 is a lot of records to iterate over. EDIT: Just checked. 2.3 billion is the number of records whose names and birthdates we'd have to do lookups on just to do a survey of this kind.

**Comment by eads** [comment]
You should run the analysis! It really isn't a ton to process (:

**Comment by bepetersn** [comment]
<h4>Here are some confirmed examples of returning inmates or recidivism: </h4>

![dmupjco](https://f.cloud.github.com/assets/1389463/951802/2f7e9c5e-03b0-11e3-9f35-a60a33bf7d23.png)

I am currently scraping the CCJ website with a new person_id field added to the inmate model ... it's going to take many hours, since I failed to set up the postgreSQL database (sqlite doesn't support concurrency as well, so I can't parallelize.) I suppose we hardly even needed such confirmation.

<b>However, I think this is a compelling reason, and a good time, to consider restructuring the whole top-level of our database, i.e. the inmate object.</b>

We could change our `Inmate`'s (and maybe even rename this) primary key to the hashed value associated with them, and give inmates a `jail_history` field, similar to the `charges_history` and `housing_history` fields that are currently associated with one stay in jail. To be more specific, the jail history would record a list of times that an individual spent in the CCJ system, a `jail_stay` if you will. A jail-stay would have all of the fields that are associated primarily with an inmate's particular stay, like their charges, housing in the jail, court date, and notably both `age_at_booking` and `booking_date`. Some other fields would be decoupled from a particular jail-stay, like height, weight, gender, race and all other personal info.

Finally, <b> I think this should take priority over a lot of other issues we are working on right now</b>, at least within the scope of this project, since when we talked to <b>people who might actually use our data</b> just the other day at the meeting, tracking individuals' jail histories over time was what they were <b>most</b> interested in.

**Comment by bepetersn** [comment]
Yeah, I was definitely wrong about that, the date I was looking at was date of birth, not different dates booked. Those individuals are simply individuals who have the same name. 

Having looked at the first 1900 inmates, none of them have returned to jail. I'll keep trying to understand this data.

**Comment by eads** [comment]
You should just write some python to hash what's in the database now.

The proposed refactoring has some problems. Generating an identifier for
each inmate... that's important. Let's make that work. The jailstay object
could essentially be what the inmate object is now. Normalizing inmate
demographics actually doesn't make sense because the way it works now, you
can see if their weight changed between visits yet by normalizing it, you
can't. But with a hashed id, this really should be called a "jail stay" and
not an inmate (which is indicated by the hashed id).

On Mon, Aug 12, 2013 at 11:42 PM, Brian Peterson
notifications@github.comwrote:

> Yeah, I was definitely wrong about that, the date I was looking at was
> date of birth, not different dates booked. Those individuals are simply
> individuals who have the same name.
> 
> Having looked at the first 1900 inmates, none of them have returned to
> jail. I'll keep trying to understand this data.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/116#issuecomment-22542929
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

Stay grimy!

**Comment by bepetersn** [comment]
I think I understand what's happening. In the jail at any given time, there can only be one record of a given inmate staying in the jail. It's only over time that an individual person first stays at the prison, then leaves, then comes back again, and might be assigned a new jail id and have a different booking date reflecting when they come back.

However, note that I have had to redefine the inmate model, and at scrape-time, get the name, birthdate, plus race and gender to create a hash of these. Since we have up til now discarded birthdate, and in particular the inmate's name, it's impossible to re-create the unique hashed id. 

So, we can't find the rate of recidivism until we have already implemented the hashing on our production server and collected data over time. All inmate data we've collected up until now can't be integrated with our tracking of individuals over time. 

I have a theory, though, that maybe all the duplicate copies of inmates in the cook county jail database are actually the result of incomplete overwriting of old inmates with returning inmates.

**Comment by bepetersn** [comment]
I hear you, Dave. No need to normalize personal data. At a minimum, though, we can tie all the data we are hashing to create a unique id with to the inmate object, instead of a jail_stay object, since we're assuming it stays the same anyway.

**Comment by bepetersn** [comment]
This is conditionally done; we need to look at the data we've collected to see if it's actually working, though.

**Comment by randy7771026** [comment]
Issue 124 - Glad to see that this comment and the following discussion made it to the issue level.  What was done?

**Comment by nwinklareth** [comment]
Brain implemented a Hash using SHA1024 and we store that. This large of a
hash means that the likelihood of collision is very very small. This was
done at end of summer 2013.

Brian also did some preliminary research on recidivism using the hash back
on November 4th. Even in that short period of time he found numerous cases
of recidivism.

Norbert

On Sat, Mar 1, 2014 at 2:38 PM, randy7771026 notifications@github.comwrote:

> Issue 124 - Glad to see that this comment and the following discussion
> made it to the issue level. What was done?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/116#issuecomment-36435843
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by randy7771026** [comment]
Yes, that was issue 116.  Perhaps issue 124 made it to the wrong project.
 I would think 124 would be for the overview project and then later
determine how to address the issues.  Mahrinah von Schlegel had a project
for victims to enter data which had some difficulties with measuring the
veracity of reports.  Many social sites have a lot of chatter on crime.
 Eventually perhaps there could be some correlation of the data.

Was there something done with that in the cookcountyjail project?
