### ISSUE TITLE
Collapse some race categories

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#118]
Having done a little bit of research, I think we can safely collapse together a couple of our race categories, including 'WH' into 'W' and 'BK' into 'B'. 

If you look at the photos associated with inmates marked 'B' for instance... there is nothing special about them, they are black. There just are only 71 records of people with race code 'B' in our pretty-large-database, while there's 34,000ish with race code 'BK'. Likewise with 'W' (79 records) and 'WH' (5800ish). The single letter form in both cases seems to be a much less common abbreviation. 

I'd love to find out more about how these things are recorded, as we hope to do in the future. But sooner or later it may make sense to collapse these 4 categorizations into 2. Perhaps we should do it with all the 'L' codes too. That seems less certain. 'LT' has nearly 5000 records, but 'LW' also has over 3000. 'LB' has much less.

**Comment by nwinklareth** [comment]
I think that this should be done for summarized data views only. The raw data entries should retain this information, in case someone wants to do an analysis at some later date on the use of these categories.

**Comment by bepetersn** [comment]
I agree with what you say about only collapsing categories for summaries.
