### ISSUE TITLE
Get Cook County Jail floorplan

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#12]

**Comment by jimglover** [comment]
What medium do we want this floor plan to be in?

**Comment by wilbertom** [comment]
![Screen Shot 2013-01-18 at 1 58 32 PM](https://f.cloud.github.com/assets/2273055/79293/88e7c5f8-61a9-11e2-962f-b4cffec9e615.png)

The only thing I could find online

**Comment by fgregg** [comment]
What about the city's building footprint file.

-Forest

On Fri, Jan 18, 2013 at 1:59 PM, Wilberto Morales
notifications@github.comwrote:

> [image: Screen Shot 2013-01-18 at 1 58 32 PM]https://f.cloud.github.com/assets/2273055/79293/88e7c5f8-61a9-11e2-962f-b4cffec9e615.png
> 
> The only thing I could find online
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/12#issuecomment-12438496.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by wilbertom** [comment]
Not sure about that stuff. However these post might help in getting an idea
of the different areas
http://www.cookcountysheriff.org/doc/doc_DivisionsOfJail.html

**Comment by fgregg** [comment]
http://www.nbcchicago.com/news/local/cOUNTY-jAIL-oFFICIALS-pLAN-TO-cLOSE--86360287.html

and

http://www.openstreetmap.org/?lat=41.842878&lon=-87.695419&zoom=18 

Seem to be what we are looking for.

**Comment by wilbertom** [comment]
This is awesome!

**Comment by wilbertom** [comment]
This seems to be usable in [26thandcalifornia](https://github.com/sc3/26thandcalifornia)
