### ISSUE TITLE
Tie hash tags to recidivism and locations with information from 911 calls, scanners and arrest records as well as information from neighborhood non-technical people. 

### ISSUE THREAD

**Issue by randy7771026** [sc3/cookcountyjail#124]

**Comment by bepetersn** [comment]
Closing in favor of separate tickets. #116, for initiating recidivism tracking itself, is already done.

**Comment by bepetersn** [comment]
The only other dataset that I know about, which we are directly able to tap is Incident Data, from city data portal.
