### ISSUE TITLE
Person ID field in database is too small

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#127]
Set to 32 characters in length, however sha256 generates a 64 character in length value

**Comment by bepetersn** [comment]
Woops. The hex value for it is you mean? 256/4 = 64, yep. Sorry, knew
there'd be some bug.

**Comment by nwinklareth** [comment]
Brain Peterson pointed out that my fix was incorrect. I modified 0014 migration file and not countyapi/model.ps file which is what I should. This is do to incorrect assumption on my part of how South works

**Comment by bepetersn** [comment]
For nearly every purpose i can think of it actually worked. However, at
least for documentation's sake we should change the model.

**Comment by nwinklareth** [comment]
Fixed see issue #137
