### ISSUE TITLE
Filtering difference between json and jsonp calls

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#133]
Noticed a difference between fetching data from DailyPopulationCounts using json and jsonp calls.

This call using json return the requested subset:
- http://cookcountyjail.recoveredfactory.net/api/1.0/dailypopulationcounts/?format=json&limit=0&booking_date__gte=2013-07-01&booking_date__lt=2013-08-01

The same call specifying jsonp, returns everything:
- http://cookcountyjail.recoveredfactory.net/api/1.0/dailypopulationcounts/?format=jsonp&callback=processJSONP&limit=0&booking_date__gte=2013-07-01&booking_date__lt=2013-08-01

Note: changed the database column name in table DailyPopulationCounts from date to booking_date to be consistent with other tables referring to the same date.

**Comment by wilbertom** [comment]
Is this still a issue? If so, where is the difference in the responses.

**Comment by nwinklareth** [comment]
Well when I just tried it now I did not see the problem I first reported so I am going to close this.

**Comment by wilbertom** [comment]
Still let's keep an eye on it just in case.
