### ISSUE TITLE
Simplify and speed up clone_db by serializing a copy of our database after each scrape

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#136]

**Comment by bepetersn** [comment]
For accomplishing what we already do, all that is necessary from the server side is as simple as: 

```
./manage.py dumdata > thedata.json
```

I guess we could then expose this data through an API? Or something. I'm not sure. It was @eads's recommendation originally. For more complex "cloning" use-cases, like only getting the data you're missing since a certain date, a wrapper around the following functionality should do the job:

```
from django.core import serializers
data = serializers.serialize("json", SomeModel.objects.filter())
```

(Discovered this functionality in [this](http://stackoverflow.com/a/11580335/1151229) StackOverflow answer.)

On the client side, you then eventually have to do something like:

```
./manage.py loaddata thedata.json
```

**Comment by eads** [comment]
No need to serve it up through the API -- look into how to serve static
files with Django and nginx. Should be easy business.

**Comment by nwinklareth** [comment]
Implemented and committed on Oct 4th.
