### ISSUE TITLE
Document V2.0 API aims / goals

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#138]
Driven by need to improve information model, based on learnings from v1.0 version.

Also to use more lighter weight technology.

Requirement document: https://docs.google.com/document/d/1ZoY-R0deM8OUGtsLfyegqE-QMwnZBp3vmbMQ3eQcXcw/edit?usp=sharing

Proposed Information Model: https://docs.google.com/drawings/d/1WAXGB1l5QcX_2XV5_VjvVNNxOO9UvGIh5jXgakNnICo/edit?usp=sharing

**Comment by bepetersn** [comment]
I've made v2.0 API a new milestone for this project. Should we maybe pull these resources out into one of our github pages / eventually our website, and close this issue?

**Comment by bepetersn** [comment]
I've made a wiki containing the contents of this issue, the info model, requirements, etc.
