### ISSUE TITLE
Set up server (EBS?)

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#14]
I'm leaning towards Elastic Beanstalk on this, which supports Django + MySQL.

**Comment by eads** [comment]
I got frustrated after days of dealing with Elastic Beanstalk and had this crap up in a little more than an hour on Heroku: http://vast-retreat-3472.herokuapp.com/ui/

**Comment by fgregg** [comment]
woot!

**Comment by eads** [comment]
One note: you will need to switch back to postgres. But it is totally worth
it -- heroku is amazing.
