### ISSUE TITLE
Dumping the database runs out of memory with Django 1.4.2

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#156]
The version of dumpdata in Django 1.4.2 loads all of the database objects into memory and serializes them into JSOM all in memory. The database has grown to be so large that this approach runs out of memory.

**Comment by eads** [comment]
There's a patch for this in Django 1.6. But maybe there's a way to define
our own command to do this instead of patching Django or running an
unstable version.

**Comment by bepetersn** [comment]
So is django v1.54 recent enough to get a better dumpdata command?

**Comment by nwinklareth** [comment]
Yes but our site does not work on Ubuntu, works on my Mac.

I get 500 on every request and I cannot figure out where it is happening.
It seems to be happening before it tries the routes.

So help, otherwise I need to revert back to Django 1.4.2 and turn off
database dumping.

Brian, can you try the new version on your machine and see it works?

And apologies.

Norbert

On Sun, Oct 6, 2013 at 4:33 PM, Brian Peterson notifications@github.comwrote:

> So was upgrading to django v1.54 good enough to get a better dumpdata
> command?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25777301
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Well, not everything is broken. Static files are still being served.

**Comment by nwinklareth** [comment]
True, and all the api calls fail.

When I set DEBUG to true then the site works, which is why it works on may
Mac.

On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson notifications@github.comwrote:

> Well, not everything is broken. Static files are still being served.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Ok, well I just noticed that the fabfile's location for
'installed_nginx_fname' is wrong. I think this is my fault, it should be:
/etc/nginx/sites-enabled/cookcountyjail.conf, where it is currently
/etc/nginx/sites-available/cookcountyjail.conf.

This might be part of the problem, but definitely not all of it. I am
thinking that it's an nginx issue. Note that there's an nginx conf in
sites-enabled under the filename 'cookcountyjail'. I'm looking into it's
contents right now.

On Sun, Oct 6, 2013 at 5:29 PM, nwinklareth notifications@github.comwrote:

> True, and all the api calls fail.
> 
> When I set DEBUG to true then the site works, which is why it works on may
> Mac.
> 
> On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson notifications@github.comwrote:
> 
> > Well, not everything is broken. Static files are still being served.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162>
> > .
> 
> ## 
> 
> Regards
> 
> ## Norbert
> 
> Norbert Winklareth
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778371
> .

## 

Brian Peterson

**Comment by nwinklareth** [comment]
Perhaps that what we should do for now, is leave DEBUG=True to get the site
back up and running?

We don't have confidential stuff that wil be revealed if people put in bad
paths

On Sun, Oct 6, 2013 at 5:29 PM, Norbert Winklareth <
norbert.winklareth@gmail.com> wrote:

> True, and all the api calls fail.
> 
> When I set DEBUG to true then the site works, which is why it works on may
> Mac.
> 
> On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson notifications@github.comwrote:
> 
> > Well, not everything is broken. Static files are still being served.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162
> > .
> 
> ## 
> 
> Regards
> 
> ## Norbert
> 
> Norbert Winklareth

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Do you mean DEBUG=True in the django app? I think you do. Anyway, that
sounds fine, if you think that will make it work.

On Sun, Oct 6, 2013 at 5:35 PM, nwinklareth notifications@github.comwrote:

> Perhaps that what we should do for now, is leave DEBUG=True to get the
> site
> back up and running?
> 
> We don't have confidential stuff that wil be revealed if people put in bad
> paths
> 
> On Sun, Oct 6, 2013 at 5:29 PM, Norbert Winklareth <
> norbert.winklareth@gmail.com> wrote:
> 
> > True, and all the api calls fail.
> > 
> > When I set DEBUG to true then the site works, which is why it works on
> > may
> > Mac.
> > 
> > On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson notifications@github.comwrote:
> > 
> > > Well, not everything is broken. Static files are still being served.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162>
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> 
> ## 
> 
> Regards
> 
> ## Norbert
> 
> Norbert Winklareth
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778491
> .

## 

Brian Peterson

**Comment by nwinklareth** [comment]
Yes in the Django app. The problem is in how we handle the configuration of
Django. There is some constraint that is applied when DEBUG=False, or some
something is ignored when DEBUG=True. That is what we need to figure out.

On Sun, Oct 6, 2013 at 5:36 PM, Brian Peterson notifications@github.comwrote:

> Do you mean DEBUG=True in the django app? I think you do. Anyway, that
> sounds fine, if you think that will make it work.
> 
> On Sun, Oct 6, 2013 at 5:35 PM, nwinklareth notifications@github.comwrote:
> 
> > Perhaps that what we should do for now, is leave DEBUG=True to get the
> > site
> > back up and running?
> > 
> > We don't have confidential stuff that wil be revealed if people put in
> > bad
> > paths
> > 
> > On Sun, Oct 6, 2013 at 5:29 PM, Norbert Winklareth <
> > norbert.winklareth@gmail.com> wrote:
> > 
> > > True, and all the api calls fail.
> > > 
> > > When I set DEBUG to true then the site works, which is why it works on
> > > may
> > > Mac.
> > > 
> > > On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson <
> > > notifications@github.com>wrote:
> > > 
> > > > Well, not everything is broken. Static files are still being served.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162>
> > > > .
> > > 
> > > ## 
> > > 
> > > Regards
> > > 
> > > ## Norbert
> > > 
> > > Norbert Winklareth
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778491>
> > .
> 
> ## 
> 
> Brian Peterson
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778519
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
I think you're right, I checked the nginx error log, there are some weird
errors happening that I need to sort out, but not while accessing
'/api/1.0', or any should-be-working address.

On Sun, Oct 6, 2013 at 5:42 PM, nwinklareth notifications@github.comwrote:

> Yes in the Django app. The problem is in how we handle the configuration
> of
> Django. There is some constraint that is applied when DEBUG=False, or some
> something is ignored when DEBUG=True. That is what we need to figure out.
> 
> On Sun, Oct 6, 2013 at 5:36 PM, Brian Peterson notifications@github.comwrote:
> 
> > Do you mean DEBUG=True in the django app? I think you do. Anyway, that
> > sounds fine, if you think that will make it work.
> > 
> > On Sun, Oct 6, 2013 at 5:35 PM, nwinklareth notifications@github.comwrote:
> > 
> > > Perhaps that what we should do for now, is leave DEBUG=True to get the
> > > site
> > > back up and running?
> > > 
> > > We don't have confidential stuff that wil be revealed if people put in
> > > bad
> > > paths
> > > 
> > > On Sun, Oct 6, 2013 at 5:29 PM, Norbert Winklareth <
> > > norbert.winklareth@gmail.com> wrote:
> > > 
> > > > True, and all the api calls fail.
> > > > 
> > > > When I set DEBUG to true then the site works, which is why it works
> > > > on
> > > > may
> > > > Mac.
> > > > 
> > > > On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson <
> > > > notifications@github.com>wrote:
> > > > 
> > > > > Well, not everything is broken. Static files are still being
> > > > > served.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162>
> > > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Regards
> > > > 
> > > > ## Norbert
> > > > 
> > > > Norbert Winklareth
> > > 
> > > ## 
> > > 
> > > Regards
> > > 
> > > ## Norbert
> > > 
> > > Norbert Winklareth
> > > 
> > > —
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778491>
> > > .
> > 
> > ## 
> > 
> > Brian Peterson
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778519>
> > .
> 
> ## 
> 
> Regards
> 
> ## Norbert
> 
> Norbert Winklareth
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778600
> .

## 

Brian Peterson

**Comment by nwinklareth** [comment]
I confirmed that if I do the following on Mac:
export CCJ_PRODUCTION=1
./manage.py runserver
curl http://127.0.0.1:8000/api/1.0/?format=json

I get: <h1>Server Error (500)</h1>%

So it most definitely an issue with the way we use Django and how Django
1.5.4 operates.

I have to go so I am going to put DEBUG=True in cookcountyjail/settings.py
and push it to the website.

And i ask that others please look into this what is causing this error.

If we cannot figure out within the next two weeks we should discuss rolling
back to an earlier verison of Django, even though that is something I
really, really would rather not do.

Norbert

On Sun, Oct 6, 2013 at 5:47 PM, Brian Peterson notifications@github.comwrote:

> I think you're right, I checked the nginx error log, there are some weird
> errors happening that I need to sort out, but not while accessing
> '/api/1.0', or any should-be-working address.
> 
> On Sun, Oct 6, 2013 at 5:42 PM, nwinklareth notifications@github.comwrote:
> 
> > Yes in the Django app. The problem is in how we handle the configuration
> > of
> > Django. There is some constraint that is applied when DEBUG=False, or
> > some
> > something is ignored when DEBUG=True. That is what we need to figure
> > out.
> > 
> > On Sun, Oct 6, 2013 at 5:36 PM, Brian Peterson notifications@github.comwrote:
> > 
> > > Do you mean DEBUG=True in the django app? I think you do. Anyway, that
> > > sounds fine, if you think that will make it work.
> > > 
> > > On Sun, Oct 6, 2013 at 5:35 PM, nwinklareth notifications@github.comwrote:
> > > 
> > > > Perhaps that what we should do for now, is leave DEBUG=True to get
> > > > the
> > > > site
> > > > back up and running?
> > > > 
> > > > We don't have confidential stuff that wil be revealed if people put
> > > > in
> > > > bad
> > > > paths
> > > > 
> > > > On Sun, Oct 6, 2013 at 5:29 PM, Norbert Winklareth <
> > > > norbert.winklareth@gmail.com> wrote:
> > > > 
> > > > > True, and all the api calls fail.
> > > > > 
> > > > > When I set DEBUG to true then the site works, which is why it
> > > > > works
> > > > > on
> > > > > may
> > > > > Mac.
> > > > > 
> > > > > On Sun, Oct 6, 2013 at 5:18 PM, Brian Peterson <
> > > > > notifications@github.com>wrote:
> > > > > 
> > > > > > Well, not everything is broken. Static files are still being
> > > > > > served.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778162>
> > > > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Regards
> > > > > 
> > > > > ## Norbert
> > > > > 
> > > > > Norbert Winklareth
> > > > 
> > > > ## 
> > > > 
> > > > Regards
> > > > 
> > > > ## Norbert
> > > > 
> > > > Norbert Winklareth
> > > > 
> > > > —
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778491>
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Brian Peterson
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778519>
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778600>
> > .
> 
> ## 
> 
> Brian Peterson
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25778707
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by nwinklareth** [comment]
I have push the fix and the website works.

Please update your copies to the latest version and please help track down
what is causing the error when DEBUG is set to False.

Thanks
Norbert

**Comment by bepetersn** [comment]
I bet this is it: http://stackoverflow.com/a/15128309/1151229. Basically,
we need an 'ALLOWED_HOSTS' setting in our settings.py. I'm not exactly sure
what our hostname is, or I would add it right now.

On Sun, Oct 6, 2013 at 6:13 PM, nwinklareth notifications@github.comwrote:

> I have push the fix and the website works.
> 
> Please update your copies to the latest version and please help track down
> what is causing the error when DEBUG is set to False.
> 
> Thanks
> Norbert
> 
> On Sun, Oct 6, 2013 at 6:02 PM, Norbert Winklareth <
> norbert.winklareth@gmail.com> wrote:
> 
> > I confirmed that if I do the following on Mac:
> > export CCJ_PRODUCTION=1
> > ./manage.py runserver
> > curl http://127.0.0.1:8000/api/1.0/?format=json
> > 
> > I get: <h1>Server Error (500)</h1>%
> > 
> > So it most definitely an issue with the way we use Django and how Django
> > 1.5.4 operates.
> > 
> > I have to go so I am going to put DEBUG=True in
> > cookcountyjail/settings.py
> > and push it to the website.
> > 
> > And i ask that others please look into this what is causing this error.
> > 
> > If we cannot figure out within the next two weeks we should discuss
> > rolling back to an earlier verison of Django, even though that is
> > something
> > I really, really would rather not do.
> > 
> > Norbert
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779157
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
Yeah, we just need to add a line to the cookcountyjail/settings.py:

ALLOWED_HOSTS = ['cookcountyjail.recoveredfactory.net']

And that should make it work. This is a known issue for upgrading from 1.4
to 1.5.

On Sun, Oct 6, 2013 at 6:17 PM, Brian Peterson bepetersn@gmail.com wrote:

> I bet this is it: http://stackoverflow.com/a/15128309/1151229. Basically,
> we need an 'ALLOWED_HOSTS' setting in our settings.py. I'm not exactly sure
> what our hostname is, or I would add it right now.
> 
> On Sun, Oct 6, 2013 at 6:13 PM, nwinklareth notifications@github.comwrote:
> 
> > I have push the fix and the website works.
> > 
> > Please update your copies to the latest version and please help track down
> > what is causing the error when DEBUG is set to False.
> > 
> > Thanks
> > Norbert
> > 
> > On Sun, Oct 6, 2013 at 6:02 PM, Norbert Winklareth <
> > norbert.winklareth@gmail.com> wrote:
> > 
> > > I confirmed that if I do the following on Mac:
> > > export CCJ_PRODUCTION=1
> > > ./manage.py runserver
> > > curl http://127.0.0.1:8000/api/1.0/?format=json
> > > 
> > > I get: <h1>Server Error (500)</h1>%
> > > 
> > > So it most definitely an issue with the way we use Django and how Django
> > > 1.5.4 operates.
> > > 
> > > I have to go so I am going to put DEBUG=True in
> > > cookcountyjail/settings.py
> > > and push it to the website.
> > > 
> > > And i ask that others please look into this what is causing this error.
> > > 
> > > If we cannot figure out within the next two weeks we should discuss
> > > rolling back to an earlier verison of Django, even though that is
> > > something
> > > I really, really would rather not do.
> > > 
> > > Norbert
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779157
> > .
> 
> ## 
> 
> Brian Peterson

## 

Brian Peterson

**Comment by nwinklareth** [comment]
Brian,

Logged into the website and try it out.

Norbert

On Sun, Oct 6, 2013 at 6:30 PM, Brian Peterson notifications@github.comwrote:

> Yeah, we just need to add a line to the cookcountyjail/settings.py:
> 
> ALLOWED_HOSTS = ['cookcountyjail.recoveredfactory.net']
> 
> And that should make it work. This is a known issue for upgrading from 1.4
> to 1.5.
> 
> On Sun, Oct 6, 2013 at 6:17 PM, Brian Peterson bepetersn@gmail.com
> wrote:
> 
> > I bet this is it: http://stackoverflow.com/a/15128309/1151229.
> > Basically,
> > we need an 'ALLOWED_HOSTS' setting in our settings.py. I'm not exactly
> > sure
> > what our hostname is, or I would add it right now.
> > 
> > On Sun, Oct 6, 2013 at 6:13 PM, nwinklareth notifications@github.comwrote:
> > 
> > > I have push the fix and the website works.
> > > 
> > > Please update your copies to the latest version and please help track
> > > down
> > > what is causing the error when DEBUG is set to False.
> > > 
> > > Thanks
> > > Norbert
> > > 
> > > On Sun, Oct 6, 2013 at 6:02 PM, Norbert Winklareth <
> > > norbert.winklareth@gmail.com> wrote:
> > > 
> > > > I confirmed that if I do the following on Mac:
> > > > export CCJ_PRODUCTION=1
> > > > ./manage.py runserver
> > > > curl http://127.0.0.1:8000/api/1.0/?format=json
> > > > 
> > > > I get: <h1>Server Error (500)</h1>%
> > > > 
> > > > So it most definitely an issue with the way we use Django and how
> > > > Django
> > > > 1.5.4 operates.
> > > > 
> > > > I have to go so I am going to put DEBUG=True in
> > > > cookcountyjail/settings.py
> > > > and push it to the website.
> > > > 
> > > > And i ask that others please look into this what is causing this
> > > > error.
> > > > 
> > > > If we cannot figure out within the next two weeks we should discuss
> > > > rolling back to an earlier verison of Django, even though that is
> > > > something
> > > > I really, really would rather not do.
> > > > 
> > > > Norbert
> > > 
> > > —
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779157>
> > > .
> > 
> > ## 
> > 
> > Brian Peterson
> 
> ## 
> 
> Brian Peterson
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779447
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Right. When i get a minute, I will.

**Comment by bepetersn** [comment]
Pull request submitted.

On Sun, Oct 6, 2013 at 7:16 PM, Brian Peterson bepetersn@gmail.com wrote:

> Right. When i get a minute, I will.
> On Oct 6, 2013 7:14 PM, "nwinklareth" notifications@github.com wrote:
> 
> > Brian,
> > 
> > Logged into the website and try it out.
> > 
> > Norbert
> > 
> > On Sun, Oct 6, 2013 at 6:30 PM, Brian Peterson notifications@github.comwrote:
> > 
> > > Yeah, we just need to add a line to the cookcountyjail/settings.py:
> > > 
> > > ALLOWED_HOSTS = ['cookcountyjail.recoveredfactory.net']
> > > 
> > > And that should make it work. This is a known issue for upgrading from
> > > 1.4
> > > to 1.5.
> > > 
> > > On Sun, Oct 6, 2013 at 6:17 PM, Brian Peterson bepetersn@gmail.com
> > > wrote:
> > > 
> > > > I bet this is it: http://stackoverflow.com/a/15128309/1151229.
> > > > Basically,
> > > > we need an 'ALLOWED_HOSTS' setting in our settings.py. I'm not
> > > > exactly
> > > > sure
> > > > what our hostname is, or I would add it right now.
> > > > 
> > > > On Sun, Oct 6, 2013 at 6:13 PM, nwinklareth notifications@github.comwrote:
> > > > 
> > > > > I have push the fix and the website works.
> > > > > 
> > > > > Please update your copies to the latest version and please help
> > > > > track
> > > > > down
> > > > > what is causing the error when DEBUG is set to False.
> > > > > 
> > > > > Thanks
> > > > > Norbert
> > > > > 
> > > > > On Sun, Oct 6, 2013 at 6:02 PM, Norbert Winklareth <
> > > > > norbert.winklareth@gmail.com> wrote:
> > > > > 
> > > > > > I confirmed that if I do the following on Mac:
> > > > > > export CCJ_PRODUCTION=1
> > > > > > ./manage.py runserver
> > > > > > curl http://127.0.0.1:8000/api/1.0/?format=json
> > > > > > 
> > > > > > I get: <h1>Server Error (500)</h1>%
> > > > > > 
> > > > > > So it most definitely an issue with the way we use Django and how
> > > > > > Django
> > > > > > 1.5.4 operates.
> > > > > > 
> > > > > > I have to go so I am going to put DEBUG=True in
> > > > > > cookcountyjail/settings.py
> > > > > > and push it to the website.
> > > > > > 
> > > > > > And i ask that others please look into this what is causing this
> > > > > > error.
> > > > > > 
> > > > > > If we cannot figure out within the next two weeks we should
> > > > > > discuss
> > > > > > rolling back to an earlier verison of Django, even though that is
> > > > > > something
> > > > > > I really, really would rather not do.
> > > > > > 
> > > > > > Norbert
> > > > > 
> > > > > —
> > > > > 
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779157>
> > > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Brian Peterson
> > > 
> > > ## 
> > > 
> > > Brian Peterson
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/156#issuecomment-25779447>
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/156#issuecomment-25780111
> > .

## 

Brian Peterson

**Comment by nwinklareth** [comment]
The ALLOWED_HOSTS change fixed issue and site is now running under Django 1.5.4 and all of the other packages updated to their latest versions.
