### ISSUE TITLE
date_updated

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#164]
When I look at the json data coming from the API, it would be nice to see the date when it was last updated in the meta section. I haven't thought through what this would mean...

**Comment by nwinklareth** [comment]
Basically, you want the scraper to log when it updated the system, Good idea. Write a story for it. Note that in the 2.0 version we do not have meta-data, do we need it don't know. Still I think it should be discussed, so what are the arguments for having meta-data delivered as part of a response, especially as I have never used it in using the 1.0 API?

**Comment by bepetersn** [comment]
I don't know if it's possible with the API we'll be making running on Flask, but the metadata information that I found most useful was that if you entered a specific query on the API, the number of people who met those criteria came up, even when there was a default limit of 100 or 1000 or whatever in place.

This brings up a lot of related issues with how we're making our API that are pretty unsettled. I was planning to try to use Flask-Restless's module for it. I don't know what features they have, or what legwork would be necessary to have this "summary" data part of a "meta" section, but it's definitely worth looking into.

**Comment by nwinklareth** [comment]
Whether this meta-information is displayed or not, and what content is displayed or not is not dependent on implementation choices, it is strictly dependent on whether we choose to implement it or not and what we specify we want displayed.

I have opened #271 specifically to add meta-data information to 2.0 API. Additionally the update_date is dependent on #246 and I am closing this one.
