### ISSUE TITLE
Determine and account for values that were causing next court date to throw errors in scraper

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#17]

**Comment by wilbertom** [comment]
Some inmates have a empty next court date field. ex: http://www2.cookcountysheriff.org/search2/details.asp?jailnumber=2012-0928093

**Comment by fgregg** [comment]
Can this issue be closed?

**Comment by eads** [comment]
Nope! We keep pushing it to the back burner.

**Comment by fgregg** [comment]
What would resolve this issue? Understanding why some inmates don't have a next court date?

**Comment by eads** [comment]
It's actually just some kind of parsing error covered over by an overly
liberal try/except block. Which is why it keeps getting pushed back, and
may not even be a thing anymore. I'll investigate and update or close the
ticket.

On Sat, Jan 19, 2013 at 10:26 PM, Forest Gregg notifications@github.comwrote:

> What would resolve this issue? Understanding why some inmates don't have a
> next court date?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/17#issuecomment-12465833.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by ryandasher** [comment]
I'd still like to look at this, so long as we can wait for a possible solution until Saturday (just assuming I'll need help).

But I'll try to take a look before our next meet.

**Comment by eads** [comment]
This is pesky, but there's no rush. I think saturday will be great.

On Tue, Jan 22, 2013 at 3:20 PM, ryandasher notifications@github.comwrote:

> I'd still like to look at this, so long as we can wait for a possible
> solution until Saturday (just assuming I'll need help).
> 
> But I'll try to take a look before our next meet.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/17#issuecomment-12567189.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by ryandasher** [comment]
Getting started on this, aww yah.

**Comment by ryandasher** [comment]
Just to update: Shared my thoughts with David on what I believe is wrong with the try/except block, so lately I've been trying to polish up that snippet of code.
