### ISSUE TITLE
Let's research Tastypie

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#19]
@Davy-jones-Giant-squid @ryandasher @codersquid @wilbertomorales @gloverjimmie -- please take a gander at http://tastypieapi.org/ and http://django-tastypie.readthedocs.org/en/latest/

**Comment by jimglover** [comment]
Should we install?

**Comment by jacobroufa** [comment]
What about https://github.com/itemshoppe/delicious-cake/ ??

Just curious. I'm not a Python guy (yet) but this is an alternative to TastyPie, developed by someone who has used it and other RESTful Django plugins.

**Comment by eads** [comment]
@jacobroufa My colleague Joe is somewhat opposed to TastyPie and Django Piston (which I used back at Fermi for a while) for the same reasons as Monsieur Delicious Cake. 

@everyone ... I think TastyPie is going to handle our needs really well. For this project, the samey-ness, simplicity, and polish of TastyPie should do us nicely. What we really need to deliver to the UI at the moment are lists of inmate records, which can be processed on the front-end. 

Where we see network and client performance issues generating summarized data in the front-end, we can create summary models and present those via the TastyPie-generated API to provide tailored data structures to the UI.
