### ISSUE TITLE
Add parameter to filter by booking date to scraper functions.

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#20]
To make scraping quicker, we need to filter for inmate records with booking date greater than some parameter, and also calculate discharge dates against the same set of records. 

The `handle`, `process_urls`, and `calculate_discharge_date` methods in scrape_inmates.py will need to get this parameter. `handle` needs to get it from the command line arguments, and then pass it as a function parameter to the other two functions.

**Comment by wilbertom** [comment]
Hey David should I implement this as a option for handle or as argument?

**Comment by eads** [comment]
This is basically irrelevant now that you're working on a polling mode and we refactored the scraper code, so I'm closing it.
