### ISSUE TITLE
Thinking about using the unique id: ambiguity issues

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#216]
I'd like to mention an issue relating to the unique id we now generate that I was thinking about.

At the outset, I want to note that the usefulness of these ids is greater the longer we maintain a single system of generating them. As of now, we have about 3 months' scraping worth of unique ids. So if we want to make changes to how we create the ids, we should do it as soon as possible. 

Currently, we hash strings that look like, for example, the following:

ALICANDRO,JOSEF01121972LM

... where this is a representation of an inmate with the following personal information:

Name: Jose F. Alicandro 
Birthdate: 01-21-1972
Race: Latino
Gender: Male

Note that the name is stored mostly the way we find it in inmate details pages (minus spaces), that is: in all caps, with last name first, followed by comma, then first name, then middle initial if there is one. 

These data might not appear cleaned, but for the most part this format is easy to reproduce with outside data. Worse, from my perspective, is the inclusion of the middle initial. Browsing over inmate records as viewable at the Sheriff's inmate locator, the middle initial is sometimes present. However, more often it is not. A full middle name appears never to be present, or at least that is the format of data as it currently being generated. 

The result of the possible inclusion of a middle initial is that even given full information about an individual, we still can't guarantee whether we have identified them in our database unless we do at least two checks: one with a middle initial, and one without. 

So I was thinking about the following proposal: 
### If there is a middle initial, don't include it in the hash

There ought to be enough information contained in the hash (race, birthdate, name) to mostly uniquely identify people without middle names. Remember that besides matching these criteria, the person also has to enter the cook county jail system, which is not very likely.

There is still possibility of false positives, of course.

This would also give us a chance to fix something else: I feel that SHA256 is an unnecessarily long hash at 64 characters, and while we are looking at hashes we should halve its length.

We could also take out the comma and otherwise normalize the identifying string we hash.

**Comment by nwinklareth** [comment]
Brian,

You wrote:

Browsing over inmate records as viewable at the Sheriff's inmate locator,
the middle initial is sometimes present.

Did you encounter a case of an inmate who was in there twice, once with the
initial and once without?

I don't have a middle name. I think that for identification purposes that
they would try and capture if the person has a middle, because that does
help to distinguish between individuals.

If we redid the information assembler and or the hashing algorithm we would
lose many of the inmates already in the system, so I vote we stay with the
existing hashing mechanism. Why step backwards? Especially when one
considers, as Brain correctly pointed out, it takes a fair bit of time,
arguably somewhere around 3 years - based on that mid-90s study, to get to
a point that we have over 80% confidence that the ratio of new offenders
versus repeat is realistic.

Norbert

On Wed, Nov 13, 2013 at 1:00 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> I'd like to mention an issue relating to the unique id we now generate
> that I was thinking about.
> 
> At the outset, I want to note that the usefulness of these ids is greater
> the longer we maintain a single system of generating them. As of now, we
> have about 3 months' scraping worth of unique ids. So if we want to make
> changes to how we create the ids, we should do it as soon as possible.
> 
> Currently, we hash strings that look like, for example, the following:
> 
> ALICANDRO,JOSEF01121972LM
> 
> ... where this is a representation of an inmate with the following
> personal information:
> 
> Name: Jose F. Alicandro
> Birthdate: 01-21-1972
> Race: Latino
> Gender: Male
> 
> Note that the name is stored mostly the way we find it in inmate details
> pages (minus spaces), that is: in all caps, with last name first, followed
> by comma, then first name, then middle initial if there is one.
> 
> These data might not appear cleaned, but for the most part this format is
> easy to reproduce with outside data. Worse, from my perspective, is the
> inclusion of the middle initial. Browsing over inmate records as viewable
> at the Sheriff's inmate locator, the middle initial is sometimes present.
> However, more often it is not. A full middle name appears never to be
> present, or at least that is the format of data as it currently being
> generated.
> 
> The result of the possible inclusion of a middle initial is that even
> given full information about an individual, we still can't guarantee
> whether we have identified them in our database unless we do at least two
> checks: one with a middle initial, and one without.
> 
> So I was thinking about the following proposal:
> If there is a middle initial, don't include it in the hash
> 
> There ought to be enough information contained in the hash (race,
> birthdate, name) to mostly uniquely identify people without middle names.
> Remember that besides matching these criteria, the person also has to enter
> the cook county jail system, which is not very likely.
> 
> There is still possibility of false positives, of course.
> 
> This would also give us a chance to fix something else: I feel that SHA256
> is an unnecessarily long hash at 64 characters, and while we are looking at
> hashes we should halve its length.
> 
> We could also take out the comma and otherwise normalize the identifying
> string we hash.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/216
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
If we assume that the data source the inmate locator uses is consistent with **itself** (_it might not be, depending on the mechanism for information gathering / entry_), then that would allow us to be confident that we are always in fact catching returning cases when they happen. 

However, I was trying to control for instances where because of the mechanism of information gathering / entry of some **other** data source, either 
- **A)** they do not record a middle name where the inmate locator does, or 
- **B)** they record a middle name where the inmate locator does not. 

Since the case where we cross-correlate with some other data source is where the type of data we're gathering becomes most interesting, and arguably there are more external data sources than our internal one, I thought it was worth taking a look at. 

---

I've just been looking at an overview of all the data currently available for all stages of the criminal justice system in Chicago, and really there doesn't seem to be that much to uniquely identify or link any other data to ours--most of it, save the fugitive list, seems to be thoroughly cleaned/anonymized/aggregated. So maybe this doesn't matter so much.
