### ISSUE TITLE
Set up new repo for user interface, clean up this repo

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#22]
The plan for the January class should be to remove UI stuff from this repository and move it to another project, probably called "fullhouse", which will be ridiculously simple: A static HTML template that anyone with git can clone and work on. Here's a general layout to start from:
- `index.html`: Load the javascript, build up the app
- `js/`
  - `js/config.js`: Global configuration variables: URL data API (defaults to fullhouse.recoveredfactory.net).
  - `js/app.js`: Backbone app.
- `css/`
  - `css/style.css`: Stylez.
- `lib/`: Librariez.

This will make environment issues essentially moot -- those who want to build out data viz side of project need a browser and git.

**Comment by jimglover** [comment]
I'm up for this.  Let's start building some character for this app.  It's going to become more real once we can point and click around with it.  I definitely want to take a shot at this ticket.

**Comment by eads** [comment]
Go for it. You should have privs to create new repo (call it 'fullhouse')
in the sc3 account. You can go ahead and follow the github directions for
creating and cloning. Then add the dirs and files I sketched out using
`mkdir` and `touch` and push it up. Then we can tackle some substantive
tickets related to building out the bones of this piece.

On Sat, Dec 22, 2012 at 10:28 AM, Jimmie Glover notifications@github.comwrote:

> I'm up for this. Let's start building some character for this app. It's
> going to become more real once we can point and click around with it. I
> definitely want to take a shot at this ticket.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/22#issuecomment-11638710.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by eads** [comment]
Once this is created, I can write up some tix for you.
