### ISSUE TITLE
API 1.0 - HousingHistory field housing_date_discovered should be set to Yesterday not Today

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#236]
This field is set by the scraper when it finds that an inmates location has been changed. While it is impossible to correctly determine when this change occurred in all instances that the scrapper runs we know that it could have happened no sooner than yesterday, as the scraper only processes yesterday and days before it. It is for this reason that I would like to change the setting of this value to yesterday, rather than today, the day the scraper is running.

To implement this change will require running a data migration that sets all values of this field back one day.

**Comment by bepetersn** [comment]
Ick, well that's an off-by-one error. If you're sure about it, you should
fix it.

On Sat, Dec 7, 2013 at 11:31 AM, nwinklareth notifications@github.comwrote:

> This field is set by the scraper when it finds that an inmates location
> has been changed. While it is impossible to correctly determine when this
> change occurred in all instances that the scrapper runs we know that it
> could have happened no sooner than yesterday, as the scraper only processes
> yesterday and days before it. It is for this reason that I would like to
> change the setting of this value to yesterday, rather than today, the day
> the scraper is running.
> 
> To implement this change will require running a data migration that sets
> all values of this field back one day.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/236
> .

## 

Brian Peterson
