### ISSUE TITLE
Generate summaries of all distinct places

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#24]
Should be as simple as querying API for CourtLocations.

**Comment by fgregg** [comment]
For the purposes of getting more info about the locations, here's a summary count for the top 100 distinct places. http://bunkum.us/top_locations.csv

There are some 5,400 distinct locations. We should figure out how to parse the location info.  I can send a link to the list to Andy.

**Comment by eads** [comment]
Sorry, I meant court locations. This is now available though: http://fullhouse.recoveredfactory.net/api/1.0/courtlocation/?format=json&limit=0
