### ISSUE TITLE
Integrate South?

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#25]
I kind of hate south. But we probably need it because we're scraping data.

**Comment by jimglover** [comment]
What is south?

**Comment by eads** [comment]
It's a library that helps django manage database changes.

**Comment by jimglover** [comment]
What's the address?

**Comment by eads** [comment]
http://south.aeracode.org/

Coordinate with sabine, this is hers!

**Comment by jimglover** [comment]
gotcha...
