### ISSUE TITLE
change API name for consistency?

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#266]
Hey all, I was just casually reviewing some of the work that was done on our original cookcountyjail API. In doing so, I came across what I think is **a lack of symmetry, if not necessarily a misstep**. 

What I realized was that we have accessible via our API, all of the following kinds of objects: courtdates, courtlocations, housinglocations; all of these are accessible, irrespective of what inmates they are associated with. This makes some sense from the perspective of the normalization of our database model. These objects are stored in their own separate tables, and are accessible with inmates if the API consumer also sets "related=1", or are actually accessible in a standalone fashion at their individual API endpoints. 

This brings me to the asymmetry I was talking about. I noticed this because though housing locations are defined separately, there's also the representation that is more inmate-related: housing history. This contrasts with charges, and with court, though:

1) although **charges have an inmate-related API, they don't have a separate API for themselves, something like "chargescitation"**, where you would be able to find a list of all charges that we know about. And 

2) I also noticed that our separately defined court APIs, **courtlocation and courtdate, don't have an inmate-related "courthistory"** API to correspond with them.

So, just pointing this out, I'm really just curious if anyone thought of this stuff before? And if it's something we want to include in our 2.0 API?

**Comment by bepetersn** [comment]
Or conversely, maybe we don't want to rely on these related database tables so much? I don't know.

**Comment by nwinklareth** [comment]
No, the charges/citations need their own table as we keep repeating the
information which is a bad DB practice. In the V2.0 logical model they have
their own separate schema.

On Sat, Mar 1, 2014 at 9:30 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Or conversely, maybe we don't want to rely on these related database
> tables so much? I don't know.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/266#issuecomment-36444964
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Well, how about a court history API?

**Comment by nwinklareth** [comment]
Yes that is in there as well. Isn't it the current v1.0 API?

On Sat, Mar 1, 2014 at 11:01 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Well, how about a court history API?
> 
> On Mar 1, 2014 10:59 PM, "nwinklareth" notifications@github.com wrote:
> 
> > No, the charges/citations need their own table as we keep repeating the
> > information which is a bad DB practice. In the V2.0 logical model they
> > have
> > their own separate schema.
> > 
> > On Sat, Mar 1, 2014 at 9:30 PM, Brian Everett Peterson <
> > notifications@github.com> wrote:
> > 
> > > Or conversely, maybe we don't want to rely on these related database
> > > tables so much? I don't know.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36444964>
> > > 
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446204>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446233
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
No, it's actually not. At least not at the level of a separate API, though
it might be if you pass the related param to the inmate API; I'd have to
check if it is there as a database table.

**Comment by bepetersn** [comment]
Also, this might well be a good place to bring it up: do we need a court
date API / table at all? Dates are something that go on and on forever, and
are better thought of us as numbers in a sequence than as unique objects
that just grow and grow our database.

It might be different if we had interesting information to associate with
the court date, like... well, a judge. See issue #53 for that.

**Comment by nwinklareth** [comment]
CourtDate is the court history table.

On Sat, Mar 1, 2014 at 11:13 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Also, this might well be a good place to bring it up: do we need a court
> date API / table at all? Dates are something that go on and on forever, and
> are better thought of us as numbers in a sequence than as unique objects
> that just grow and grow our database.
> 
> It might be different if we had interesting information to associate with
> the court date, like... well, a judge. See issue #53 for that.
> 
> On Mar 1, 2014 11:07 PM, "nwinklareth" notifications@github.com wrote:
> 
> > Yes that is in there as well. Isn't it the current v1.0 API?
> > 
> > On Sat, Mar 1, 2014 at 11:01 PM, Brian Everett Peterson <
> > notifications@github.com> wrote:
> > 
> > > Well, how about a court history API?
> > > 
> > > On Mar 1, 2014 10:59 PM, "nwinklareth" notifications@github.com
> > > wrote:
> > > 
> > > > No, the charges/citations need their own table as we keep repeating
> > > > the
> > > > information which is a bad DB practice. In the V2.0 logical model
> > > > they
> > > > have
> > > > their own separate schema.
> > > > 
> > > > On Sat, Mar 1, 2014 at 9:30 PM, Brian Everett Peterson <
> > > > notifications@github.com> wrote:
> > > > 
> > > > > Or conversely, maybe we don't want to rely on these related
> > > > > database
> > > > > tables so much? I don't know.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36444964
> > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Regards
> > > > 
> > > > ## Norbert
> > > > 
> > > > Norbert Winklareth
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446204
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446233>
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446319>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446429
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
I see. I had to take a glance at all of these APIs to make sure I
understood. So all of the "history" objects are actually single couplings
between an inmate and another object. In other words, they are not
"histories" per se, they are elements of a history that that inmate can be
said to have in relation to the entire collection of objects from a given
table (charge, court, or housing) with which they are associated.

At any rate, that's how it is for courtdate and housinghistory. Which is
why you said there was a repetitiveness to the chargeshistory object,
because we reference "charges" and a "charges_citation" each time, rather
than an "citation_id", or some reference to a separate charges object.

Now I want to change the name "housinghistory" in v2.0, because it confused
me. Or "courtdate", I guess. Not sure which.

The idea of DRYing up the database with regard to charges brings us at
least partially back to the issue #113: how to parse/categorize them.

On Sat, Mar 1, 2014 at 11:16 PM, nwinklareth notifications@github.comwrote:

> CourtDate is the court history table.
> 
> On Sat, Mar 1, 2014 at 11:13 PM, Brian Everett Peterson <
> 
> notifications@github.com> wrote:
> 
> > Also, this might well be a good place to bring it up: do we need a court
> > date API / table at all? Dates are something that go on and on forever,
> > and
> > are better thought of us as numbers in a sequence than as unique objects
> > that just grow and grow our database.
> > 
> > It might be different if we had interesting information to associate with
> > the court date, like... well, a judge. See issue #53 for that.
> > 
> > On Mar 1, 2014 11:07 PM, "nwinklareth" notifications@github.com wrote:
> > 
> > > Yes that is in there as well. Isn't it the current v1.0 API?
> > > 
> > > On Sat, Mar 1, 2014 at 11:01 PM, Brian Everett Peterson <
> > > notifications@github.com> wrote:
> > > 
> > > > Well, how about a court history API?
> > > > 
> > > > On Mar 1, 2014 10:59 PM, "nwinklareth" notifications@github.com
> > > > wrote:
> > > > 
> > > > > No, the charges/citations need their own table as we keep repeating
> > > > > the
> > > > > information which is a bad DB practice. In the V2.0 logical model
> > > > > they
> > > > > have
> > > > > their own separate schema.
> > > > > 
> > > > > On Sat, Mar 1, 2014 at 9:30 PM, Brian Everett Peterson <
> > > > > notifications@github.com> wrote:
> > > > > 
> > > > > > Or conversely, maybe we don't want to rely on these related
> > > > > > database
> > > > > > tables so much? I don't know.
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36444964
> > > > > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Regards
> > > > > 
> > > > > ## Norbert
> > > > > 
> > > > > Norbert Winklareth
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446204
> > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446233
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Regards
> > > 
> > > ## Norbert
> > > 
> > > Norbert Winklareth
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446319>
> > > 
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446429>
> > 
> > .
> 
> ## 
> 
> Regards
> 
> ## Norbert
> 
> Norbert Winklareth
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/266#issuecomment-36446474
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
So then, the "asymmetry" I mentioned is really just in charges, and we're going to fix that in the v2.0 API, I guess.

**Comment by bepetersn** [comment]
See issue #267 for getting this whole thing fixed, it could be awhile off still, but it's the API endpoint I most want to create.

**Comment by bepetersn** [comment]
@nwinklareth, @eads, what do you think about changing the name of the "courtdate" API to "courthistory", for symmetry's sake. The first part of good documentation is good naming, and consistency is arguably the most important part of that.

**Comment by bepetersn** [comment]
Well, it's too late to do this, I think! Maybe I can convince Wil for v2.
