### ISSUE TITLE
Document new scraper

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#274]
This is primarily for the new concurrent scraper.

**Comment by wilbertom** [comment]
How are we documenting. Just a wiki or file comments?

**Comment by bepetersn** [comment]
Is this done satisfactorily, then? I suppose we're waiting on more commentary.

**Comment by nwinklareth** [comment]
Is it satisfactory, only reviewers can answer that which is why I asked that the documentation be reviewed and based on the feedback I'll add more if needed.

**Comment by bepetersn** [comment]
I edited the intro paragraphs. But I think the majority of the content is good.
