### ISSUE TITLE
Clean up the V1.0 API commands 

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#278]
There are a number of commands that are no longer needed, and some of them should not be run again. So they should be removed.

**Comment by bepetersn** [comment]
Did you know that you can close issues automatically if you say, in the
commit message, "fixed" (or done equivalents) and include a reference to
the issue #?

Just a quick fact.

**Comment by nwinklareth** [comment]
No I did not know that. Thanks will do so in future commits.

On Sun, Mar 9, 2014 at 1:02 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> Did you know that you can close issues automatically if you say, in the
> commit message, "fixed" (or done equivalents) and include a reference to
> the issue #?
> 
> Just a quick fact.
> On Mar 9, 2014 12:59 AM, "nwinklareth" notifications@github.com wrote:
> 
> > Closed #278 https://github.com/sc3/cookcountyjail/issues/278.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/278>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/278#issuecomment-37120725
> .

## 

Regards

## Norbert

Norbert Winklareth
