### ISSUE TITLE
Error on migration #21 "set_in_jail_housing_location"

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#282]
```
 - Migration 'countyapi:0021_set_in_jail_housing_location' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: countyapi:0021_set_in_jail_housing_location
DoesNotExist: HousingLocation matching query does not exist.
```

**Comment by bepetersn** [comment]
I can confirm this error, running from a clean repo and clean environment (excluding stuff I didn't think of, like my OS).

**Comment by bepetersn** [comment]
Reproduced this error outside the context of a migration, by running the basic code that the migration file itself contains in a shell:

![screenshot from 2014-03-25 01 32 16](https://f.cloud.github.com/assets/1389463/2508995/a8d5b4f6-b3e7-11e3-802e-daba22a12a0c.png)

Still trying to parse out what this may imply.

**Comment by bepetersn** [comment]
So, it appears that the "HousingLocation matching query", which is being run in this migration, and which is causing this `DoesNotExist` error is in fact just this -- the list of _not in jail_ categories is being run in a get request against an empty database. 

Perhaps this is the canonical Migration error, one which South is supposed to resolve. I'm now curious to do some research into what **exactly** South does. Based on these results, I'm going to do a bunch more research on these kinds of issues, maybe just some more thinking.

**Comment by bepetersn** [comment]
Ah, so here we have the fundamental issue. If I HAD a populated database, I'd have these housing location objects in it, and therefore this migration would probably succeed, from what I can tell. But given that I don't have a populated database, I can't migrate my tables to match the version of the database tables that we're now using. This then leads to problems loading a copy of the database onto my machine. I just tried to clone the database:

![screenshot from 2014-03-25 03 07 01](https://f.cloud.github.com/assets/1389463/2509531/d53b1d62-b3f4-11e3-9b50-27abc2280148.png)

So, I can't populate my database unless my database is already populated. Excepting some other method than these very basic ones that I have run through.

**Comment by bepetersn** [comment]
By commenting out the section of the code that was causing an error in countyapi/migrations/0021_set_in_jail_housing_location.py, I was able to complete my migrations, and then load the database.

This code is as follows:

```
for hlnij in housing_locations_not_in_jail:
    housing_location = orm.HousingLocation.objects.get(housing_location=hlnij)
    housing_location.in_jail = False
    housing_location.save()
for housing_location in orm.HousingLocation.objects.all():
    if housing_location.in_jail is None:
        housing_location.in_jail = True
        housing_location.save()
```

I believe this section of code, which is clearly supposed to set the in_jail field on our housing_location objects may not be necessary, and we could just get rid of it. If this field needs to get set in your local database, you can clone our master database. What are other reasons that one might need to have non-null "in_jail" fields in their local?

What do you think, @wilbertom? @nwinklareth?

**Comment by bepetersn** [comment]
I wonder if we're using South correctly. Lots of these migrations are doing things that, with an empty database, do nothing. Plenty of them, unlike this 21st migration, just loop over all existing entries in the database--which doesn't fail with an empty database, just does nothing, as long as the sql table exists. 

But it begs the question of whether or not most of them need the auto-generated code in them to be run either.

**Comment by nwinklareth** [comment]
You do not have to do the migration to load the database, you just need to
initialize the schema.

That code was part of the data migration I did to get that field set. I
think that the way I wrote it is wrong, it does not properly protect itself
against the current definition of the field.

Commenting it out is fine.

Norbert

On Tue, Mar 25, 2014 at 3:15 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> By commenting out the section of the code that was causing an error in
> countyapi/migrations/0021_set_in_jail_housing_location.py, I was able to
> complete my migrations, and then load the database.
> 
> I believe this section of code, which is clearly supposed to set the
> in_jail field on our housing_location objects may not be necessary, and we
> could just get rid of it. If this field need to get set in your local
> database, you can clone our master database. What are other reasons that
> one might need to have non-null "in_jail" fields in their local?
> 
> What do you think, @wilbertom https://github.com/wilbertom? @nwinklarethhttps://github.com/nwinklareth
> ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/282#issuecomment-38614664
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Yes, initializing the schema, that is exactly what I meant. The migration
itself is just the running of a python file containing so much code. Part
of it is the code I am taking about commenting out, which is an iteration
over the data. The other part is a redefinition of the database models, the
schema.

Anyway, I will go ahead the merge.
