### ISSUE TITLE
CCJ Database corrupted by issue #285

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#296]
Entries from booking date of March 17th moving forward were corrupted by error reported in #285.

The fix is to restore the database from the dump made on the 19th and tomorrow's scraper run will fill in the missing entries.

**Comment by bepetersn** [comment]
So there were changes made to the page structure of the website? It looked similar, but I didn't check the HTML.

**Comment by bepetersn** [comment]
Is this fixed now, because we're looking at past days in our passes on the sheriff's site?

**Comment by bepetersn** [comment]
Closing...
