### ISSUE TITLE
changing reqs.txt location likely broke some of our fab commands

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#299]
This should really be documented somewhere...

**Comment by bepetersn** [comment]
On second thought, perhaps it did not. I just successfully completed a build using the commands we had setup, `fab production master deploy`.

Thoughts, @nwinklareth?

**Comment by nwinklareth** [comment]
I fixed the fab file.

On Wed, Apr 2, 2014 at 5:42 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> On second thought, perhaps it did not. I just successfully completed a
> build using the commands we had setup, fab production master deploy
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/299#issuecomment-39315461
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Oh, you already did? So I can close this?

**Comment by nwinklareth** [comment]
Yes, please.

Norbert
