### ISSUE TITLE
Scrape all fields from inmate pages and assign to inmate record

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#3]
This is in `countyapi/management/commands/scrape_inmates.py` around line 90. You'll want to process and map specific columns to each InmateRecord field.

**Comment by eads** [comment]
Whoops, this was closed last week.

**Comment by fgregg** [comment]
The court date and court location info are not being scraped.

**Comment by eads** [comment]
You probably just need to reset your db:

`python manage.py sqlreset countyapi | python manage.py dbshell`

Eventually, we'll do migrations with south. But for local dev destroying your db and starting over is the way to go.
