### ISSUE TITLE
move all static files on server into our github repo 

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#331]
W'ere missing the "api.html" file.  We need to keep better track of these things. 

Also extend the build sequence that automatically updates the correct files on the server if the github repo changes. See the current `fabfile.py` for an idea of how this might be done.

**Comment by wilbertom** [comment]
Wait what do you mean lol? The files should had never left the git repo.

**Comment by bepetersn** [comment]
The "API" page isn't there. Can't remember just now if there are others.

On Wed, May 7, 2014 at 10:36 AM, Wilberto Morales
notifications@github.comwrote:

> Wait what do you mean lol? The files should had never left the git repo.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/331#issuecomment-42442842
> .

## 

Brian Peterson

**Comment by wilbertom** [comment]
Ok cool. I'll hunt them down and put them back on the v2.0. Do we really need it for v1?

**Comment by wilbertom** [comment]
Here's [api.html](https://github.com/sc3/cookcountyjail/blob/master/templates/api.html)
