### ISSUE TITLE
Change CountyInmate.booking_date field to be date field

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#355]
This was created as a date and time field, yet bookings are only by date. Additionally this field allows for nulls and in fact some of the fields contain nulls. Also to do a SQL based analysis based on booking date is very difficult with the datetime type.Hence the request to make the type change to the field.

**Comment by wilbertom** [comment]
Yup, let's make sure we don't make the same mistake in v2.0.

**Comment by wilbertom** [comment]
I see you did a data migration. Can we close this?

**Comment by bepetersn** [comment]
I believe we can now close this.
