### ISSUE TITLE
Charges fields are being saved empty

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#36]

**Comment by eads** [comment]
Can we close this?

**Comment by wilbertom** [comment]
We should. When I looked at it, it was saving the right empty charges. It might be better to save them better as a null?

**Comment by eads** [comment]
Yeah, that's a good idea. Plus a migration to turn empty strings into null
values. So let's close this and make a follow up ticket.

On Tue, Apr 2, 2013 at 1:49 AM, Wilberto Morales
notifications@github.comwrote:

> We should. When I looked at it, it was saving the right empty charges. It
> might be better to save them better as a null?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/36#issuecomment-15758641
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by wilbertom** [comment]
Charges fields are already null but for some reason tastypie shows the as ""
