### ISSUE TITLE
Scraping failed as of May 3rd

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#367]
Code changes in issue #342 move location of cron.sh without updating crontab entry to point to the new location.

**Comment by nwinklareth** [comment]
Superceded by #372.

**Comment by bepetersn** [comment]
Did the scraper fail entirely yesterday, then? Should we restart it again?

**Comment by nwinklareth** [comment]
Yes it failed yesterday. I got busy last night and did not check until this
morning when I found that it had also failed.

I made a fix by relaxing the model and then hand installed it and then add
a cron entry to run it.

It ran successfully and I will keep monitoring it over the next week.

On Sun, May 11, 2014 at 3:33 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Did the scraper fail entirely yesterday, then? Should we restart it again?
> On May 11, 2014 1:54 PM, "nwinklareth" notifications@github.com wrote:
> 
> > Closed #367 https://github.com/sc3/cookcountyjail/issues/367.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/367#event-119916721>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/367#issuecomment-42782312
> .

## 

Regards

## Norbert

Norbert Winklareth
