### ISSUE TITLE
test_pgsql_installation fails on the server, while apparently trying to load our new models

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#381]
Here is a gist showing the results of running the test locally (by setting CCJ_PRODUCTION env variable). It looks like what happens is Postgres tries to load all of our models (because of `db.create_all()`, with the `db` object imported from `ccj.app`. 

A couple of points:
- I don't think this should be happening, we might have to figure out how to use a test database with Flask and Postgres
- But at the same time it looks like it's failing; the error is something like it's failing to create an ENUM field, because it requires a name for the field. Maybe that problem is legitimate?

I would like to use this as a wedge to start using the pgsql database as we have decided we're going to, re: #365. In the meantime, I am going to relax the restriction of not deploying without passing tests, which our v2 fabfile has, because I would like to see if the v2 scraper can run successfully tomorrow (all of the real tests do pass).

**Comment by wilbertom** [comment]
Brian the enum column was missing a `name` needed for postgres. I noticed this when switching databases. I fixed it but haven't pushed because I need to finish other stuff first.

**Comment by bepetersn** [comment]
You should push to your github repo so people can see your work.

**Comment by bepetersn** [comment]
I'm just going to delete this stupid test.
