### ISSUE TITLE
Look into csv output 

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#39]

**Comment by eads** [comment]
Check out http://django-tastypie.readthedocs.org/en/v0.9.11/serialization.html#implementing-your-own-serializer -- there's an example of a CSV serializer that should be fairly robust. This is currently a fairly high priority ticket -- @Davy-jones-Giant-squid, can you get to this in the next few days? If not, I'll swap this ticket for one with @wilbertomorales.

**Comment by Davy-jones-Giant-squid** [comment]
Do you want me to add a csv serializer in the countyapi's models.py?

**Comment by eads** [comment]
You should put it in api.py I think, but yes, that's the plan!

On Fri, Jan 11, 2013 at 2:38 PM, Davy-jones-Giant-squid <
notifications@github.com> wrote:

> Do you want me to add a csv serializer in the countyapi's models.py?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/39#issuecomment-12162357.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir
