### ISSUE TITLE
handle discharging of inmates for v2

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#419]
Since we are decoupling scraper and API, the API will need to handle its own discharging, but it CAN provide a route to initiate discharging, perhaps an HTTP UPDATE method?

The scraper can then call this discharge route with each successive inmate. This seems to make the most sense, it basically parallels what we do currently, except that it requires the v2 API to do all of its own work.

Thoughts, @wilbertom? I would like to get a very clear idea of what this will look like.

**Comment by nwinklareth** [comment]
How this works should follow how adding or updating an Inmate entry is done and there is no design for the data loader. The design and implementation of the loader is covered by #445.
