### ISSUE TITLE
Parsing the location fields

### ISSUE THREAD

**Issue by fgregg** [sc3/cookcountyjail#42]
We need to understand the location code in order to figure out whether a person is in jail, on electronic monitoring, awol, or otherwise disposed. 

We might also want to do further parsing so that we could figure out which building and tier an inmate is in. This could be very nice for visualization purposes, but could also lead to insights about the internal operations of the jail.

These documents are a start: https://docs.google.com/spreadsheet/ccc?key=0AptDdMTTIKEndDdJUEhNMXhWWDhDMHVQejRWZEtoeFE https://docs.google.com/spreadsheet/ccc?key=0AptDdMTTIKEndGs3ZUdKTlpRdFVzMG1YRXFVbkVKeFE

But they don't completely square with how the Sheriff describes the jail: http://www.cookcountysheriff.org/doc/doc_DivisionsOfJail.html

For example is division 03-\* the residential treatment unit or an auxillary?

**Comment by fgregg** [comment]
We may also learn some things by looking at the visitation pages: http://www.cookcountysheriff.org/googlemap/map_docdivision2.html

**Comment by eads** [comment]
That looks incredibly promising.

On Fri, Jan 18, 2013 at 3:43 PM, Forest Gregg notifications@github.comwrote:

> We may also learn some things by looking at the visitation pages:
> http://www.cookcountysheriff.org/googlemap/map_docdivision2.html
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/42#issuecomment-12442332.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by fgregg** [comment]
Division I locations start with 01-*

http://www.cookcountysheriff.com/googlemap/map_docdivision1.html

Division II locations begin with 02 followed by a building ID, i.e. 02-D1-*
is a dorm that is in the D1 building of Division II

Locations in the division II auxillary building start with 03-AX

http://www.cookcountysheriff.com/googlemap/map_docdivision2.html

Locations starting with 03-A-1, 03-A-2, 03-A-3, 03-B-1, 03-B-2, 03-B-3 are in the Residential treatment unit .
http://www.cookcountysheriff.com/googlemap/map_docdivision3.html

Locations starting with 04-\* are in Division IV http://www.cookcountysheriff.com/googlemap/map_docdivision4.html

Locations starting with 05-\* are in Division V http://www.cookcountysheriff.com/googlemap/map_docdivision5.html

Locations starting with 06-\* are in Division VI http://www.cookcountysheriff.com/googlemap/map_docdivision6.html

Locations starting with 08 are the Cermack hospital http://www.cookcountysheriff.com/googlemap/map_docdivision8.html

Locations starting with 09 are in division 9 http://www.cookcountysheriff.com/googlemap/map_docdivision9.html

Similar for 10 http://www.cookcountysheriff.com/googlemap/map_docdivision10.html

Locations starting with 11 are division 11, except maybe for 11-DR http://www.cookcountysheriff.com/googlemap/map_docdivision11.html

Locations starting with 14 are division 14 http://www.cookcountysheriff.com/doc/doc_division14.html

These are the remaining unresolved locations
https://docs.google.com/spreadsheet/ccc?key=0AptDdMTTIKEndElkYlE5NVYtS3hLYjBhRWRuZUNZUkE

**Comment by wilbertom** [comment]
The first draft for the housing location parsing is pushed. It needs a lot of review. Some areas are:
1. Improving the Algorithm to be shorter and better
2. Making sure all information is being saved right and there is no data loss
3. Thinking about a better models so that more metadata can be extracted from the housing locations
4. Researching and narrowing to when exactly we can say an inmate is in the jail or not.  
5. Reviewing the models reverse relationships 
6. Improve it to be able to catch exceptions 
7. After all of that then dropping the housing_location field from the CountyInmate class  
8. Implement the new models on the API

**Comment by wilbertom** [comment]
We are Parsing them, next step would be to test the new parser.
