### ISSUE TITLE
Capturing of Raw Inmate Data failed

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#437]
This affected Issue #429.

The reason that capturing the raw inmate data failed is that the existence checks for the release and build directories failed and the reason they failed is that the locations specified in the scraper.sh do not exist. In addition to this there is a problem that the two directories were specified as being the same.

The first problem resulted from the path specified in Nginx config file, which exists, not being specified in scraper.sh for the Release directory and that the specified directory did not exist. This mismatch was not caught as no external review of the changes occurred nor is there a test environment to catch these types of problems. The Build Directory was specified as being the same as the Release directory and so it too did not exist.

The second problem of the Release and Build directories being the same is the result of a set of communication failures:
- The issue for the specification of the release directory did not state that it should not be the same as the build directory.
- The build directory issue did state that the two directories must not be the same, howver it was implemented by the original author of this functionality and was also closed.
- A wiki page describing the configuration options needed to specify the locations of these two directories was written but not linked to from any of the issues.
  - This occurred because of an accidental erasing of the text of issue #435 prior to saving it and then after it was re-written the text was not checked to make sure that it linked to the configuration options descriptions.
- The original author did not descripe the the naming convention used during construction

**Comment by bepetersn** [comment]
I believe I have patched this correctly with #438, which has been deployed
to the server, but we'll now need to wait another day.
