### ISSUE TITLE
Add court date API documentation

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#45]
Who wants this? The interface works the same as locations and inmates, see http://cookcountyjail.recoveredfactory.net/api/1.0/courtdate/?format=json and http://cookcountyjail.recoveredfactory.net/api/1.0/courtdate/?format=json&related=1

**Comment by ghing** [comment]
@MiseryPanda and I started writing these docs at https://github.com/sc3/cookcountyjail/wiki/API-guide-%28Start-here!%29

We still need to provide examples of filtering the list resource once #55 is merged.

**Comment by wilbertom** [comment]
Closed in favour of #393. This model doesn't exist anymore
