### ISSUE TITLE
403 in readme.md

### ISSUE THREAD

**Issue by janearc** [sc3/cookcountyjail#454]
The link to "[26th and california](http://26thycalifornia.recoveredfactory.net/v1.0/)" in [readme.md](https://github.com/sc3/cookcountyjail/blob/master/README.md#cook-county-jail-data-project) is 403. Makes it hard to see what's going on with the data?

**Comment by wilbertom** [comment]
Thanks @avriette, it's fixed.

**Comment by randy7771026** [comment]
Showed this to Wil and he fixed it using my computer.
