### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#46]
See https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers

**Comment by eads** [comment]
I don't see your cooooode (:

**Comment by Davy-jones-Giant-squid** [comment]
Sorry, I thought I did, but I've just realized by code is not finished yet. Will push asap

**Comment by eads** [comment]
No problem! Take your time (:

**Comment by eads** [comment]
No problem! Take your time (:
On Feb 2, 2013 5:09 PM, "Davy-jones-Giant-squid" notifications@github.com
wrote:

Sorry, I thought I did, but I've just realized by code is not finished yet.
Will push asap

—
Reply to this email directly or view it on
GitHubhttps://github.com/sc3/cookcountyjail/issues/46#issuecomment-13039046.
