### ISSUE TITLE
Housing Location discrepancy

### ISSUE THREAD

**Issue by jacobroufa** [sc3/cookcountyjail#47]
Looking at the API's JSON output and comparing it to the search page, every piece of data is correct except housing_location. @wilbertomorales and I wrote a single inmate scraper to pull one inmates data and compare it to the JSON output, and the data is scraped correctly.

So... this happens somewhere between the database and output. Anyone have any idea?

**Comment by fgregg** [comment]
Can you give an example urls?

On Sat, Feb 9, 2013 at 2:37 PM, Jake Roufa notifications@github.com wrote:

> Looking at the API's JSON output and comparing it to the search page,
> every piece of data is correct except housing_location. @wilbertomoraleshttps://github.com/wilbertomoralesand I wrote a single inmate scraper to pull one inmates data and compare it
> to the JSON output, and the data is scraped correctly.
> 
> So... this happens somewhere between the database and output. Anyone have
> any idea?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/47..

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by jacobroufa** [comment]
http://www2.cookcountysheriff.org/search2/details.asp?jailnumber=2013-0208208

^^ this is the inmate that we've looked at as an example. The data seems to be alright in my local database. I'm going to look at the live DB here in a second, with @eads' help.

**Comment by jacobroufa** [comment]
Ok... So we looked at the live database and the data was incorrect there. Re-scraped the above-mentioned inmate and the housing_location changed/updated to reflect the current data. I don't think we actually have a bug here, but have just discovered that the sheriff updates their data at some point.

We should check anything that we know is different now, to see that it's changed tomorrow. If the data is correct, we know it's good.
