### ISSUE TITLE
Create fabfile to deploy to Amazon EC2

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#58]
Needs to be able to:
- Setup/teardown db
- Create virtualenv
- Clone/manipulate repo
- Place configuration files in the correct locations
- Bounce cache
- Restart services
- Deploy frontend repo to Amazon S3

**Comment by wilbertom** [comment]
Should we use Fabric?

**Comment by eads** [comment]
That's what I'm sayin' (:

On Tue, Apr 2, 2013 at 8:31 AM, Wilberto Morales
notifications@github.comwrote:

> Should we use Fabric?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/58#issuecomment-15774931
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by eads** [comment]
This is done!
