### ISSUE TITLE
Should 26thandcalifornia be a subrepo of this project for easy deployment to S3?

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#59]

**Comment by wilbertom** [comment]
I think it should all be one app. It makes sense to have them separated as different repos. It separates the back end from the visual stuff. However when presenting the project to other people it feels nice to have a UI built in.

**Comment by eads** [comment]
Yeah, I'm inclined to suggest we include the frontend in the cookcountyjail
repo, just so people can get at it a little more easily.

On Tue, Apr 2, 2013 at 1:47 AM, Wilberto Morales
notifications@github.comwrote:

> I think it should all be one app. It makes sense to have them separated as
> different repos. It separates the back end from the visual stuff. However
> when presenting the project to other people it feels nice to have a UI
> built in.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/59#issuecomment-15758563
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by fgregg** [comment]
This sounds like a good case for submodules:
http://git-scm.com/book/en/Git-Tools-Submodules

On Tue, Apr 2, 2013 at 10:12 AM, David Eads notifications@github.comwrote:

> Yeah, I'm inclined to suggest we include the frontend in the
> cookcountyjail
> repo, just so people can get at it a little more easily.
> 
> On Tue, Apr 2, 2013 at 1:47 AM, Wilberto Morales
> notifications@github.comwrote:
> 
> > I think it should all be one app. It makes sense to have them separated
> > as
> > different repos. It separates the back end from the visual stuff.
> > However
> > when presenting the project to other people it feels nice to have a UI
> > built in.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/59#issuecomment-15758563>
> > .
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> “The awful thing about life is this: everyone has their reasons.” -- Jean
> Renoir
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/59#issuecomment-15781135
> .

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by eads** [comment]
26thandcalifornia has it's own deployment process... we'll leave it this way for now.
