### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#6]
I need to brush up on writing Django tests.

**Comment by ghing** [comment]
It might be useful to generate a fixture using the dumpdata management command to bootstrap the test database for testing the various Resource classes.  

Should the data be sanitized? I'm not sure how I feel about people's inmate admission records living forever in a git repo history. In the past, I've written a script using the [name_generator](https://github.com/macropin/random-name-generator) package to replace real names with random ones.

Finally, the data set is big and slicing it/anonymizing it might be a little bit cumbersome or time consuming.  It's probably a good idea to start writing some (failing) tests to get a better sense of what should be in the fixtures.

**Comment by eads** [comment]
This needs to become part of our practice and we need specific tickets.

To address @ghing's comments from way back, we don't track any names nor do we keep the DOB (just the age at booking), so there's very little to identify people once they've dropped out of the system.
