### ISSUE TITLE
API fields with whitespace

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#62]
API fields who have whitespace in their primary keys do not generate a resource uri. Underneath the hood tastypie call `django.core.urlresolvers.reverse` who doesn't support whitespace. It might on a newer of django though.

```
{

    "division": "",
    "housing_location": "C BONDING C",
    "in_jail": null,
    "in_program": "",
    "resource_uri": "",
    "sub_division": "",
    "sub_division_location": ""

},
{

    "division": "",
    "housing_location": "CELL",
    "in_jail": null,
    "in_program": "",
    "resource_uri": "/api/1.0/housinglocation/CELL/",
    "sub_division": "",
    "sub_division_location": ""

}
```

**Comment by bepetersn** [comment]
Wow, never knew about this. Does this still happen? I can't even remember if we updated Django for v1.0 API.

**Comment by bepetersn** [comment]
We did update Django to 1.6, I believe. I don't think we even use the resource URIs for anything at this point, however, so this may be a non-issue.
