### ISSUE TITLE
Some records do not have a booking date and have wrong length of stays

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#63]
Records from the days, 2012/12/22, 20912/12/23 & 2012/12/28 do not have booking date and their length of stay is also wrong.

**Comment by bepetersn** [comment]
@nwinklareth, is this related to #75 at all?

**Comment by nwinklareth** [comment]
Yes.

On Sat, Mar 1, 2014 at 8:56 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> @nwinklareth https://github.com/nwinklareth, is this related to #75https://github.com/sc3/cookcountyjail/issues/75at all?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/63#issuecomment-36444417
> .

## 

Regards

## Norbert

Norbert Winklareth
