### ISSUE TITLE
Not capturing all prisoners

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#64]
According to the website prisoner with Jail Id of 2013-0404007 exists, http://www2.cookcountysheriff.org/search2/details.asp?jailnumber=2013-0404007, yet this person is not in the database. Upon inspection I found over 10 prisoners that exist in the Cook County Jail, booked on April 4th, 2013, that are not in the database.

**Comment by eads** [comment]
There are three possibilities for why this might be.

I discovered a bug yesterday in the housing location parser.

And Wil alerted me to a bug in the scrapers general error handling logic --
pages with 500 errors cause incorrect discharge dates.

And sometimes there are just gaps in the inmate records.

The upshot is we need better error handling and even moreso better testing.

**Comment by eads** [comment]
Seems like the recent improvements by @nwinklareth have us close to resolution on this.

**Comment by nwinklareth** [comment]
David,

As I just got the new collection system to run successfully this morning, I
was going to let it run for a few more days and if it is successful then I
would say that this is resolved.

On Sat, Jul 27, 2013 at 11:16 AM, David Eads notifications@github.comwrote:

> Seems like the recent improvements by @nwinklarethhttps://github.com/nwinklarethhave us close to resolution on this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/64#issuecomment-21667945
> .

## 

Regards

## Norbert

Norbert Winklareth
