### ISSUE TITLE
Calculate discharge time

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#7]
When processing, we'll probably want to compare the jail_ids that are harvested with jail_ids of people in the database without a discharge date. That should give us all the inmates who fell out of the system since that last time we ran the scraper. We can then assign an inferred discharge date to their record.

**Comment by fgregg** [comment]
Alternatively, we could use the booking data as the beginning date. Everytime we revisit a page, we can increment a 'last seen' field. If the last field field is the day before yesterday, we can take it as the discharge date.

**Comment by eads** [comment]
I think we're on the same page: I was assuming we would calculate a "booking day" based on the jail_id, along with a seen time. 

The tricky bit is the revisiting a page: The page won't exist if the inmate was discharged, which is why I think we need to query for jail ids not present in a full scrape that also don't have a discharge date. If I've got it right, that set defines the group of inmates who've been discharged/otherwise left the system.

**Comment by eads** [comment]
I have added a functional version of this to the app in https://github.com/sc3/cookcountyjail/commit/af3ae4a7828be34bba27a47ccffd289613870249 but it still needs some finesse -- it only works with full scraping runs.
