### ISSUE TITLE
Run full poll on the server

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#71]
Back up the db and run the full poll. It might make sense to combine this with the previous ticket.

**Comment by bepetersn** [comment]
Hm, can anyone explain what this was? Whether it's still important?

**Comment by nwinklareth** [comment]
This was related to #70, which was closed sometime ago, I also ran a search for missing inmates last summer which addressed this, it also is related to how the new scraper looks for new inmates and has a sliding window that it searches for inmates that were not picked up in the first.

I am closing this as it has been done.
