### ISSUE TITLE
Use poll mode for scraper

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#72]
Needs some testing first...

**Comment by eads** [comment]
@nwinklareth -- this is invalid now, correct?

**Comment by nwinklareth** [comment]
This was something I wanted to discuss. When I ran the audit it found over
800 inmates using polling. What I wanted to do was to check if these
inmates showed up in the alphabetical lists or not. This is easy to
determine, there is a list of the found inmates and the scrapper logs when
it starts the discharge pass. If one of these inmates last_seen_date is
later then the start of the dispatch pass we know that it was not in the
alphabetical list, which seems to indicate that we need to poll. Thoughts?

On Sat, Jul 27, 2013 at 11:17 AM, David Eads notifications@github.comwrote:

> @nwinklareth https://github.com/nwinklareth -- this is invalid now,
> correct?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/72#issuecomment-21667967
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by nwinklareth** [comment]
This was implemented first in #243 because of the addition of CAPTCHA on the search form page and then as part of the next generation scraper, #249.
