### ISSUE TITLE
Audit the database audit

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#75]
Go over the database audit and make sure it all seems to work and doesn't miss anything. After that we can run it on the database

**Comment by wilbertom** [comment]
I think that Norbert's updated proposed version of the audit takes care of this.

**Comment by wilbertom** [comment]
Should the old audit be deleted?

**Comment by bepetersn** [comment]
Is there still a need to go over our database's contents? I feel sufficiently separated by time from our old data to just say "screw it".

**Comment by nwinklareth** [comment]
I found that there were bad database entries in HousingHistory. I think that we still need to do a proper data integrity audit.

**Comment by bepetersn** [comment]
I see. Do you mind my asking what data integrity means in this context?  We
have a dataset where something like 7 or 8 times out of 10, we know that
there are large holes / mistakes with it.

For most of this data, it's my understanding that we can't recover or
reproduce it.

**Comment by nwinklareth** [comment]
For instance in HousingHistory we had duplicate entries for the same
person, same location, same day, that is not supposed to happen. I think
that there is possibly the same problem with court history and both court
locations and housing locations need to be examined to make sure that we do
not have duplicates.

On Sat, Mar 1, 2014 at 8:32 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> I see. Do you mind my asking what data integrity means in this context? We
> have a dataset where something like 7 or 8 times out of 10, we know that
> there are large holes in it.
> 
> For most of this data, it's my understanding that we can't recover or
> reproduce it.
> On Mar 1, 2014 8:27 PM, "nwinklareth" notifications@github.com wrote:
> 
> > I found that there were bad database entries in HousingHistory. I think
> > that we still need to do a proper data integrity audit.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/75#issuecomment-36443947>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/75#issuecomment-36444047
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by nwinklareth** [comment]
I think that Wilberto's initial point has been dealt with and so I am closing this issue. There are however some issues with the database that should be addressed and that should be done by creating new issues that address these ones individually.
