### ISSUE TITLE
Server-side caching still not working

### ISSUE THREAD

**Issue by bepetersn** [sc3/cookcountyjail#78]
<h2>Before</h2>

What Dave did with the Nginx config file does not seem to have achieved our ideal goal; what I understand that goal is, correct me if I'm wrong: 

We need to keep our data within reach and ready to be served from the recoveredfactory.com/api/1.0/ site at all times to clients asking for it (except at minimum for a few minutes right after we do a scrape).

<h2>Current state</h2>

It IS the case that in-browser caching currently works; for instance, if you load the 26thandcalifornia app once, it loads within only a few seconds the 2nd time. But this is hardly a working condition for our project.

Since the API is the endpoint of the ccj project, django-tastypie actually provides a way to do caching for us, if you let it. Wil and I were looking at the tastypie docs not too long ago trying to figure out where exactly our data is cached, but I'm pretty sure the answer is simply this: nowhere.

<h2>TODO</h2>

Yeah, no default caching mechanism or location is configured in settings.py, under the CACHES variable (https://docs.djangoproject.com/en/dev/topics/cache/#setting-up-the-cache), so we need to set up WHERE and HOW we cache from among several options.

The second piece we're missing is actually WHAT we're caching (https://docs.djangoproject.com/en/dev/topics/cache/#the-per-site-cache). Maybe we could cache our whole "site" directly, but if we didn't want to, we could instead cache the HTTP response we're sending out (whatever it is!), or just pre-formatted data, like json. The only problem is I don't really know how to cache the json, or our response for that matter, since our views are configured so abnormally for a Django app. 

So... I welcome your contributions at this point.

**Comment by eads** [comment]
Brian, the caching appears to be working from this end. 

What you describe (and the headers I see) are why I believe this. A fast second load and headers that look like this (on second load):

"""
Cache-Control:s-maxage=720, max-age=720
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json
Date:Mon, 15 Jul 2013 21:34:21 GMT
Server:gunicorn/0.17.2
Transfer-Encoding:chunked
Vary:Accept
X-Cached:HIT
"""

However, what we need to do is "prime" the cache and set a much longer cache lifetime for the caching to be effective. Priming the cache means pre-caching the full dataset by firing an http request for it. Then if we up the cache lifetime to something on the order of a day, the full dataset will always be cached. 

Nginx caching is very simple and easy to maintain. It's a good match for the situation at hand: 1) We have a relatively small database (even expensive queries are pretty fast).  2) I did some profiling of the API library we use and found that a lot of the rendering time is spent encoding the characters in the json output.

The Django caching stuff is nice, but my experience at the Trib is that it's more trouble than it's worth vis a vis simply nginx caching.

**Comment by bepetersn** [comment]
Ah, so you think it's caching for 12 minutes (720 seconds) at a time, and
only after one of us loads all the resources? I guess that might match what
I was seeing the other day.

But that's weird. I can see from the headers you posted where the nginx
conf added a header for status: "X-Cached:HIT". But at the same time, 720
seconds isn't the value set in nginx.conf; there, the cache is set to be
valid for 60 minutes, which is definitely not happening.

**Comment by eads** [comment]
Yup, that's exactly it and I'm pretty darn sure this is the right path to
take. We use a similar cache priming technique at the trib using varnish
for the crime site. And we're using nginx caching along these lines for a
bunch of new projects, including API driven stuff.

So the real trick is a) debugging the nginx conf to get max age working
properly, b) getting nginx caching to respect a cache buster query string,
c) primiting cache.

**Comment by bepetersn** [comment]
If I may suggest, I was troubleshooting the caching, and I do know that the
tastypie caching was set to cache for 720 seconds exactly. I don't know if
that's just a coincidence, but is it possible the settings from the caching
systems are cascading together ... or something? However, I can't think of
how to test this. I just changed line 384 in countyapi/api.py from "cache =
SimpleCache(timeout=720)" to a timeout of 3600 in my local, but I guess I'd have to
host multiple servers to see this take effect.
