### ISSUE TITLE
Sketch out basic API

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#8]

**Comment by fgregg** [comment]
@eads, we may want to move this to the wiki

_Population
Number of inmates in the jail on a given date
*_ Possible to segment by charge
*\* Possible to segment by housing location
*\* Segmented by bond
- Residence of current population
  How long the incarcerated population on a given date had been in jail

*\* By day
*\* By charge
(Maybe by housing location?)
- Inflow/Outflow
  For a given date how many people came into and left the system
  *\* Segmented by charged
  *\* Segmented by location
  *\* Segmented by bond

_Length of stay
For a given date, what is distribution of lengths of stays for people booked in on that date
*_ Segmented by charge
*\* Segmented by bond

**Comment by eads** [comment]
This is great. I'll add something about binning by different time buckets (low priority until data is built up).

**Comment by eads** [comment]
Oh yah: https://github.com/sc3/cookcountyjail/wiki/API-specification

**Comment by jimglover** [comment]
Could we also include some ethnic data:  race and sex of inmate?

**Comment by fgregg** [comment]
Sounds good to me. Will you edit the wiki page?

**Comment by jimglover** [comment]
Sure.  I think we should add race and gender possible segmentation to Population, InFlow/OutFlow, and Length of  Stay searches.  What do you think?

**Comment by jimglover** [comment]
How about this?: https://github.com/sc3/cookcountyjail/wiki/API-specification

**Comment by fgregg** [comment]
Looks good to me. 

Do we want to do anything more with bail? It might be nice to see how money is flowing through this system too.

**Comment by jimglover** [comment]
Yeah, I'd like to see what the bail is for given charges and how charges vary.  Is there high bail for minor charges and how does that bail compare to major charges?  How many people even make bail?  How many get out on I-Bond?  ...Something to that affect.

**Comment by eads** [comment]
I don't think, with the current data, we'll be able to know if people make
bail. The bail / charges disparity would be do-able, and fascinating.

**Comment by jimglover** [comment]
Exactly, that's the affect I was looking for.  People are bound to wonder if there's any social justice to criminal justice at 26th and California.

**Comment by fgregg** [comment]
How about this https://github.com/sc3/cookcountyjail/wiki/API-specification

On Mon, Dec 10, 2012 at 1:14 PM, selfmaster notifications@github.comwrote:

> Exactly, that's the affect I was looking for. People are bound to wonder
> if there is any social justice to criminal justice at 26th and California.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/8#issuecomment-11212614.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by ryandasher** [comment]
You have to consider that we don't know an inmate's prior conviction history or the judge who is setting the bail, which probably have an impact on the amount of bail being set.

It's unfortunate, as I'd be interested in analyzing specific judges' bail amounts.

**Comment by jimglover** [comment]
Nice. Forest.

**Comment by fgregg** [comment]
How do we want to handle support requests for disaggregated data?

Do we want to return a csv that gives all the info for inmates who entered
the system with a given period?

On Thu, Dec 13, 2012 at 1:28 PM, selfmaster notifications@github.comwrote:

> Nice. Forest.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/8#issuecomment-11349002.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647
