### ISSUE TITLE
Reverse compatibility has been broken

### ISSUE THREAD

**Issue by wilbertom** [sc3/cookcountyjail#89]
Hey hackers!

I call dips on this issue. I haven't been around the project so it's going to take me around a week to fix this one. I have to learn how we are parsing the housing locations and how the new models work. 
# Problem

In the data migrations there we some functions that got used that no longer exists. This needs to be fixed because when a new contributor tries to migrate to the new models, it is going to be impossible. 

```

  File "/Users/wilberto/Code/freegeek/cookcountyjail/countyapi/migrations/0003_housing_location_to_housing_history.py", line 6, in <module>
    from countyapi.management.commands.utils import process_housing_location
ImportError: cannot import name process_housing_location

```

**Comment by bepetersn** [comment]
@nwinklareth and I saw this problem, I think, just the other day. A work-around we found (not exactly a fix) is just to drop the database in the "ccj" file at the root of our project. Then run `syncdb` and `migrate`, like normal. 

Maybe this isn't a fix for your problem, or we need to work out a better one. Let me know.
