### ISSUE TITLE
Is in_jail field always null?

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#96]
Paging @wilbertom

**Comment by wilbertom** [comment]
The idea behind that field is that we find out whether an inmate is actually in the jail or not. Right now for example when they are AWOL, it can be set to False.

**Comment by eads** [comment]
What are the possible values and how should they be interpreted?

**Comment by wilbertom** [comment]
True, False, Null

True: the housing location is located in the Cook County Jail

False: the inmate is in the system but not actually housed in the jail.

Null: We don't know enough about the housing location to pick true or false

**Comment by eads** [comment]
I haven't had a chance to check, but how reliably are these being parsed?

**Comment by nwinklareth** [comment]
The changes that Brian and another person, whose name I forgot, plus a fix
I made have greatly improved the parsing of this information.

If we could figure out if a person is in a jail or not would be a good
thing.

Norbert

On Tue, Jul 30, 2013 at 6:45 PM, David Eads notifications@github.comwrote:

> I haven't had a chance to check, but how reliably are these being parsed?
> On Jul 30, 2013 11:41 AM, "Wilberto Morales" notifications@github.com
> wrote:
> 
> > True, False, Null
> > 
> > True: the housing location is located in the Cook County Jail
> > 
> > False: the inmate is in the system but not actually housed in the jail.
> > 
> > Null: We don't know enough about the housing location to pick true or
> > false
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/96#issuecomment-21803147>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/96#issuecomment-21831242
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by fgregg** [comment]
What's the status of this?

**Comment by bepetersn** [comment]
The 'in-jail' field is associated with a HousingLocation object. There are currently 6434 housing locations that we know about; their uniqueness is not necessarily guaranteed (I don't know enough right now to say more). At any rate, of these, only 29 locations have non-null values. Of these, all of them have the 'in_jail' field set to False. Here's a list of these:

15-EM
15-LV
17-SFFP
15-EMAW
15-KK
15-DR
15-DRAW
01-DR
02-DR
03-AX-DR
03-DR
04-DR
05-DR
06-DR
08-2E-DR
08-2N-DR
08-2S-DR
08-2W-DR
08-3E-DR
08-3N-DR
08-3S-DR
08-3W-DR
08-DR
10-DR
11-DR
15-US
16-BC-DR
17-SFFPAW
17-WR-DR

You can see everything we know about these HousingLocations by querying the API. For example, taking the first non-null location from the above list:

http://cookcountyjail.recoveredfactory.net/api/1.0/housinglocation/?format=json&housing_location=15-EM

Here, you can see that the related "in_program" field is also set, in this case to "Electronic Monitoring". In truth, if you look at the implementation of housing location parsing, in_jail is only set to False for a few special cases:
- if "DR" is part of the location string, which we interpret as "Day Release"
- similarly, "DRAW", which we interpret as "Day Release, AWOL"
- if the location is in division 15 and contains "EM", which we interpret as "Electronic Monitoring"
- similarly for "EMAW", which we interpret as "Electronic Monitoring, AWOL"
- similarly for "KK", "LV", or "US", which we interpret as indicating other counties.
- if the location is in division 17 and contains "MOMS", which we interpret as the offsite "MOMs program"
- similarly for "SFFP" and "SFFPAW", which is interpeted as "Sherrif Female Furlough Program"

---

I think that for now we just leave everything as null unless we know for sure that it is False. Accordingly, if you want to work with the in_jail field, you can interpret a null value as "assumed to be True". Having not actually designed this part of our scraper, I can't say much more.

**Comment by eads** [comment]
How will this be handled in 2.0?

On Mon, Nov 4, 2013 at 11:27 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> The 'in-jail' field is associated with a HousingLocation object. There are
> currently 6434 housing locations that we know about; their uniqueness is
> not necessarily guaranteed (I don't know enough right now to say more). At
> any rate, of these, only 29 locations have non-null values. Of these, all
> of them have the 'in_jail' field set to False. Here's a list of these:
> 
> 15-EM
> 15-LV
> 17-SFFP
> 15-EMAW
> 15-KK
> 15-DR
> 15-DRAW
> 01-DR
> 02-DR
> 03-AX-DR
> 03-DR
> 04-DR
> 05-DR
> 06-DR
> 08-2E-DR
> 08-2N-DR
> 08-2S-DR
> 08-2W-DR
> 08-3E-DR
> 08-3N-DR
> 08-3S-DR
> 08-3W-DR
> 08-DR
> 10-DR
> 11-DR
> 15-US
> 16-BC-DR
> 17-SFFPAW
> 17-WR-DR
> 
> You can see everything we know about these HousingLocations by querying
> the API. For example, taking the first non-null location from the above
> list:
> 
> http://cookcountyjail.recoveredfactory.net/api/1.0/housinglocation/?format=json&housing_location=15-EM
> 
> Here, you can see that the related "in_program" field is also set, in this
> case to "Electronic Monitoring". In truth, if you look at the
> implementation of housing location parsing, in_jail is only set to False
> for a few special cases:
> - if "DR" is part of the location string, which we interpret as "Day
>   Release"
> - similarly, "DRAW", which we interpret as "Day Release, AWOL"
> - if the location is in division 15 and contains "EM", which we
>   interpret as "Electronic Monitoring"
> - similarly for "EMAW", which we interpret as "Electronic Monitoring,
>   AWOL"
> - similarly for "KK", "LV", or "US", which we interpret as indicating
>   other counties.
> - if the location is in division 17 and contains "MOMS", which we
>   interpret as the offsite "MOMs program"
> - similarly for "SFFP" and "SFFPAW", which is interpeted as "Sherrif
>   Female Furlough Program"
> 
> ---
> 
> I think that for now we just leave everything as null unless we know for
> sure that it is False. Accordingly, if you want to deal work with the
> in_jail parameter, you can interpret a null value as "assumed to be True".
> Having not actually designed this part of our scraper, I can't say much
> more.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/96#issuecomment-27704382
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by fgregg** [comment]
Thanks! How does this relate to the the housing location parser? What would
we need to know about housing locations to set 'in_jail' to true?

https://github.com/sc3/cookcountyjail/issues/42

On Mon, Nov 4, 2013 at 11:31 AM, David Eads notifications@github.comwrote:

> How will this be handled in 2.0?
> 
> On Mon, Nov 4, 2013 at 11:27 AM, Brian Everett Peterson <
> notifications@github.com> wrote:
> 
> > The 'in-jail' field is associated with a HousingLocation object. There
> > are
> > currently 6434 housing locations that we know about; their uniqueness is
> > not necessarily guaranteed (I don't know enough right now to say more).
> > At
> > any rate, of these, only 29 locations have non-null values. Of these,
> > all
> > of them have the 'in_jail' field set to False. Here's a list of these:
> > 
> > 15-EM
> > 15-LV
> > 17-SFFP
> > 15-EMAW
> > 15-KK
> > 15-DR
> > 15-DRAW
> > 01-DR
> > 02-DR
> > 03-AX-DR
> > 03-DR
> > 04-DR
> > 05-DR
> > 06-DR
> > 08-2E-DR
> > 08-2N-DR
> > 08-2S-DR
> > 08-2W-DR
> > 08-3E-DR
> > 08-3N-DR
> > 08-3S-DR
> > 08-3W-DR
> > 08-DR
> > 10-DR
> > 11-DR
> > 15-US
> > 16-BC-DR
> > 17-SFFPAW
> > 17-WR-DR
> > 
> > You can see everything we know about these HousingLocations by querying
> > the API. For example, taking the first non-null location from the above
> > list:
> > 
> > http://cookcountyjail.recoveredfactory.net/api/1.0/housinglocation/?format=json&housing_location=15-EM
> > 
> > Here, you can see that the related "in_program" field is also set, in
> > this
> > case to "Electronic Monitoring". In truth, if you look at the
> > implementation of housing location parsing, in_jail is only set to False
> > for a few special cases:
> > - if "DR" is part of the location string, which we interpret as "Day
> >   Release"
> > - similarly, "DRAW", which we interpret as "Day Release, AWOL"
> > - if the location is in division 15 and contains "EM", which we
> >   interpret as "Electronic Monitoring"
> > - similarly for "EMAW", which we interpret as "Electronic Monitoring,
> >   AWOL"
> > - similarly for "KK", "LV", or "US", which we interpret as indicating
> >   other counties.
> > - if the location is in division 17 and contains "MOMS", which we
> >   interpret as the offsite "MOMs program"
> > - similarly for "SFFP" and "SFFPAW", which is interpeted as "Sherrif
> >   Female Furlough Program"
> > 
> > ---
> > 
> > I think that for now we just leave everything as null unless we know for
> > sure that it is False. Accordingly, if you want to deal work with the
> > in_jail parameter, you can interpret a null value as "assumed to be
> > True".
> > Having not actually designed this part of our scraper, I can't say much
> > more.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/96#issuecomment-27704382>
> > .
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> "Medical statistics will be our standard of measurement: we will weigh
> life
> for life and see where the dead lie thicker, among the workers or among
> the
> privileged." -- Rudolf Virchow
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/96#issuecomment-27704725
> .

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by bepetersn** [comment]
@eads : 

Well, I am having a very difficult time right now querying the API (even as helpful as tastypie is) so I can see just the people that are located in-jail vs. out. The null field makes it difficult. For this reason if not for simple common sense, I'd prefer to discriminate much more, calling most locations True, unless we have reason to question this. 

The larger issue, as I see it, is the API itself. Having moved away from Django, we won't have the power of its unique querying available to our API as we did with Tastypie, where, for instance, we (could have) implemented functionality like the following to get all people who are currently in jail:

/api/1.0/countyinmate/?format=json&discharge_date_earliest__is_null=false&housing_location__in_jail=True

Especially since we plan to have a person model with a jail_history field---the result being that essentially every field we're interested in is at least one related table away---being able to chain filters and reference related tables will be very important. 

For this reason, I'm thinking about using something like [Flask-Restless](https://flask-restless.readthedocs.org/en/latest/) as our API, if it provides any significant amount of the built-in solutions we need.

**Comment by bepetersn** [comment]
If we want to be any more certain about whether or not a housing location is in jail, the fact is we have to do research and specifically probably ask someone associated with the sheriff's office. 

However, where there's no evidence to the contrary, I think it's totally reasonable to assume that a housing location is in jail. 

Either way, to belatedly answer @eads and @fgregg, we should develop a doc or spreadsheet, or something like that--some abstractable resource for determining how a location should be parsed, especially if we are interested in doing further research.

Personally, improving our understanding of housing locations is not my highest priority for now, but @fgregg has continued to point out how there are some real holes in it. 

See issue #209 for some of these gaps in our understanding.

**Comment by bepetersn** [comment]
This issue has been fixed, by someone. Probably by @nwinklareth, if I had to guess, since he's been doing most of the work on this project lately. But very few housing locations have the in_jail field set to null any more. Most are true. 64 are false. I almost feel like doing a `git bisect` to figure out when / by whom this was changed. But it's probably not worth it.

**Comment by eads** [comment]
You can use git blame to get the history of a line.

On Fri, Mar 7, 2014 at 2:02 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Closed #96 https://github.com/sc3/cookcountyjail/issues/96.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/96
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
